hortonworks/cloudbreak-images

- Makefile
- saltstack/salt/cloud-init/init.sls
- saltstack/salt/java/init.sls
- saltstack/salt/prerequisites/packages.sls
- saltstack/salt/prerequisites/pip.sls
- saltstack/salt/prerequisites/repository.sls
- saltstack/salt/prerequisites/usr/bin/ssh-aliases
- saltstack/salt/prerequisites/usr/bin/user-data-helper.sh
- saltstack/salt/salt/init.sls
> remove pub key addition because this is not important

- Vagrantfile
- scripts/salt-install.sh
- scripts/salt-setup.sh
* pip have to be importable in order to salt use it
* fix a typo in function name
> Fix centos6 pip related errors

- saltstack/base/salt/prerequisites/repository.sls
- scripts/salt-install.sh
Remove duplicated epel repo installation.
Remove multiple  apt-get update
> Remove duplicated epel repo installation.

- saltstack/hortonworks/pillar/hdp/init.sls
> Mpack url default value is empty string if not defined

- README.dev.md
Hi @doktoric @sposetti 
I added the information about copying the JAR file.
Please review and update as needed.
How do we maintain this repo? Do we create release-specific versions or just maintain master?
> Include JDBC connector's JAR for MySQL or Oracle

- saltstack/base/salt/dhcp/etc/dhcp/dhclient-enter-hooks
- saltstack/base/salt/prerequisites/usr/bin/user-data-helper.sh
- saltstack/base/salt/salt/etc/salt/minion.d/grains.conf
@doktoric @keyki merge if it should be in 2.7.1 or wait for the release and we put it in 2.7.2
> BUG-105976 Configure network interface in salt grains runtime instead of image burning

- saltstack/optional/pillar/oracle-java/init.sls
- saltstack/optional/salt/oracle-java/init.sls
* update apt cache at the start of the image build
* fix oracle jdk installation at non-interactive prompt
* install unlimited-jce-policy
> SUST-1201 Fix Oracle JDK on Debian and Ubuntu

- README.dev.md
Based on customer case this troubleshooting guide can help with custom images.
> EAR-9884 followup docs

- Makefile
- packer.json
- saltstack/base/salt/postgresql/init.sls
- saltstack/base/salt/prerequisites/disable-unattended-upgrades.sls
- scripts/salt-install.sh
Fixed ubuntu14 "jobs"
install nvme-cli
Skip 20auto-update modification (Ubuntu14 hasn't got this file)
change "runuser" to "su" because in trusty repo the util-linux package version is 2.20 the runuser command arrived in v2.23
> Ubuntu14 fix

- saltstack/hortonworks/salt/fluent/init.sls
install dbus plugin (created on CLDR side) from a public repo
> DISTX-200. Install fluentd dbus plugin on DistroX/SDX clusters.

- saltstack/hortonworks/salt/fluent/init.sls
install CLDR specific fluent azure plugin with built-in version
> DISTX-40. Install CLDR fluent azurestorage plugin

- saltstack/hortonworks/salt/metering/init.sls
do not merge yet, package needs to be tested
edit: can be merged now, package is fixed
> Use long term rpm location for metering package

- packer.json
- saltstack/base/salt/postgresql/init.sls
This reverts commit 5a1072ac629ef5be2db393d7bf20cb4ad490a33d.
> Revert "Revert "Fix debian9 image creation""

- saltstack/base/salt/fluent/init.sls
related with: https://github.com/hortonworks/cloudbreak/pull/6851
> DISTX-316. Add fluent-plugin-detect-exceptions plugin for td-agent

- saltstack/base/salt/fluent/init.sls
[DO NOT MERGE YET]
adding azurestorage_gen2 plugin
> CB-4774. Fluentd azurestorage plugin process leaking memory

- saltstack/base/salt/fluent/init.sls
updating azure storage version
testing is in progress
edit: manual tests done, looking good
> CB-4946. Update fluentd azure storage version

- Makefile
- docker/centos7.3/Dockerfile
- docker/centos7.4/Dockerfile
- docker/centos7.5/Dockerfile
- docker/centos7.6/Dockerfile
- saltstack/base/salt/postgresql/init.sls
- added docker push goal to makefile for ycloud
- systemctl reenable was failing in docker environemnt so now we manually create a symlink to the original postgres-9.6 service file
- service user for docker repository request is pending
(only tested with ycloud image)
- added yarn-private directory creation to Dockerfile as it was create to late in the process
> CB-4983 manually creating symlink for ycloud postgres service

- saltstack/base/salt/fluent/init.sls
there is a regex related bug in version 0.1.1, fixed in 0.1.2
> CB-5408. Update fluent reduction plugin version

- saltstack/base/salt/prerequisites/corkscrew.sls
- saltstack/base/salt/prerequisites/init.sls
- saltstack/base/salt/prerequisites/usr/bin/user-data-helper.sh
> Configure SSH client on gateway nodes to relay tcp traffic over proxy using Corkscrew

- scripts/azure-copy.sh
tested: http://build.eng.hortonworks.com:8080/job/cloudbreak-multi-packer-image-builder-salt-v3/583/
> CB-6368 azure image copy does not work properly

- saltstack/base/salt/prerequisites/pip.sls
related with: https://github.com/hortonworks/cloudbreak/pull/7372
> CB-5557. Add pip dependencies for CM metrics collector

- saltstack/base/salt/fluent/init.sls
related to https://github.com/hortonworks/cloudbreak/pull/7817
> CB-5966. Update dbus version (support proxies for DBus)

- saltstack/freeipa/salt/freeipa/init.sls
This just add the freeipahealth agent rpm to the pre-warmed AMI.
> CB-6898: Add freeipahealth agent to pre warmed AMI

- saltstack/base/salt/fluent/init.sls
- support write only operations -> update azure storage version
related with: https://github.com/hortonworks/cloudbreak/pull/8377
> Update azure storage version (support write only mode)

- README.dev.md
CB-8070 Clean up the advanced readme as well. Supported OS is CentOS, supported cloud platforms: AWS, Azure
> CB-8070 Clean up the advanced readme

- saltstack/hortonworks/salt/pre-warm/tmp/pre_warm_parcels.py
This PR contains the following improvements
-Handle curl exit codes and log them
-Retry downloads
-SHA verification
> CB-8436 Pre-warmed parcel download improvements

- saltstack/base/salt/cis-controls/init.sls
- saltstack/base/salt/top.sls
Added hardening checks as per https://jira.cloudera.com/browse/CB-8897
> CB-8897 - Disable unwanted filesystems

- README.image-content.md
- README.md
Simple readme file provides the list of the package content of images.
> CB-9426: Prewarmed Image BOM

- saltstack/base/salt/cis-controls/init.sls
- saltstack/base/salt/top.sls
CB-8933:  CIS - Harden SSH Configurations.
> CB-8933 - CIS - Harden SSH Configurations

- saltstack/base/salt/cis-controls/init.sls
- saltstack/base/salt/top.sls
Reverts hortonworks/cloudbreak-images#475
> Revert "CB-8933 - CIS - Harden SSH Configurations"

- Makefile
- saltstack/base/salt/fluent/init.sls
related to: https://github.com/hortonworks/cloudbreak/pull/9321
> CB-9513. Start using cdp-logging-agent instead of td-agent.

- saltstack/base/salt/cis-controls/init.sls
Addressing findings produced by aws inspector aligned with CIS-Benchmark for CentOS v1.0.
> CB-8933: CIS - Harden SSH Configurations_part1

- saltstack/base/salt/top.sls
This reverts commit f757d4c2fc73c2d8f883479b8b809144e1a6e76b, reversing
changes made to 4e73ec72118741e74bcc107608ae8e6020a5e50f.
> Revert "Merge pull request #486 from bormanbhaskar/cis-defaults"

- Makefile
Reverts hortonworks/cloudbreak-images#491
> Revert "CB-10334 adding af-south-1 and ap-south-1 and eu-south-1 to the supor…"

- Makefile
- build-ycloud-prewarm
- scripts/salt-setup.sh
All occurrence of version 3000.2 are changed to 3000.5.
> CB-10206: Update the Salt version to 3000.5

- saltstack/base/salt/cis-controls/init.sls
- Added SSH Warning Banner.
- Removed FAT from list since it's in use for centOS in GCP.
- Other code improvements.
> CB-8933:CIS-Code Improvement

- saltstack/base/salt/top.sls
Enforcing CIS Controls to run as default.
> Running CIS controls as Defaults

- Makefile
Test image is burnt and tests are done according to: https://jira.cloudera.com/browse/CB-10367?focusedCommentId=4234672&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-4234672
> CB-10367 - We shall switch to CentOS 7.9

- saltstack/base/salt/top.sls
This reverts commit b8cb51e04a9f28af475f949664eb3625453d12d7.
> Revert "Running CIS controls as Defaults"

- saltstack/base/salt/ccmv2-inverting-proxy-agent/init.sls
- saltstack/base/salt/prerequisites/usr/bin/user-data-helper.sh
- Fixed the proxy URL
- Fixed the agent key deciphering command
- Upgraded the agent to a newer version
> CB-10902: Various fixes related to running the CCMv2 agent

- saltstack/base/salt/cis-controls/init.sls
This branch has following updates. All the changes were tested and passed validations.
https://jira.cloudera.com/browse/CB-8919
https://jira.cloudera.com/browse/CB-8927
https://jira.cloudera.com/browse/CB-8928
> CIS: CB-8928+CB-8927+CB-8919

- Makefile
- scripts/packer.sh
- scripts/sparseimage/packer.sh
tested by: http://build.eng.hortonworks.com:8080/job/cloudbreak-multi-packer-image-builder-salt-v3/2670/console
> CB-10334 CB-11250 adding new eu-south-1 af-south-1 regions to aws

- Makefile
- scripts/packer.sh
- scripts/sparseimage/packer.sh
Reverts hortonworks/cloudbreak-images#529
> Revert "CB-10334 CB-11250 adding new eu-south-1 af-south-1 regions to aws"

- Makefile
Reverts hortonworks/cloudbreak-images#530
> Revert "Revert "CB-10334 CB-11250 adding new eu-south-1 af-south-1 regions to aws""

- Makefile
- build-ycloud-prewarm
The Salt version is upgraded to 3000.8
> CB-11444: Upgrade Salt to 3000.8

- saltstack/final/salt/cis-controls/init.sls
Addressed https://jira.cloudera.com/browse/CB-11681
> CB-11681: Removed printing TMOUT output on ssh

- saltstack/base/salt/prerequisites/packages.sls
- saltstack/freeipa/salt/ipaconsistency/init.sls
- saltstack/freeipa/salt/top.sls
- scripts/generate-delta-package-list.sh
Checkipaconsistency tool is installed to freeipa images.
> CB-11695: Add FreeIPA consistency check to image

- .gitignore
- scripts/azure-copy.sh
Remove leading whitespaces from Azure regions, and add file to gitignore.
> CB-9881 Fix images_in_regions

- saltstack/base/salt/nginx/etc/nginx/ssl.conf
Add a response header in our nginx so we can check if the request reached nginx,
or failed between CB - CCM
> CB-13209 Add custom nginx response header

- Makefile
- saltstack/base/salt/prerequisites/firewall.sls
- saltstack/base/salt/prerequisites/packages.sls
- saltstack/hortonworks/pillar/java/init.sls
- saltstack/hortonworks/salt/java/init.sls
- scripts/salt-install.sh
CDPR-20 Install python3-devel package for redhat7
CDPR-24 Uniq yum.conf
CDPR-26 Ignore redhat-rhui.repo file replace when file is missing
CDPR-30 Fix OpenJDK install by removing not needed modules
CDPR-31 Turn off firewall temporarily
CDPR-25 Increase space of /opt instead of symlinking to /mnt
CDPR-33 Remove awscli
CDPR-8 Fix AZURE_IMAGE_SKU Makefile variable
> CDPR-7 RHEL image burning

- saltstack/base/salt/prerequisites/firewall.sls
- saltstack/base/salt/prerequisites/init.sls
- saltstack/base/salt/prerequisites/repository.sls
- saltstack/base/salt/prerequisites/storage.sls
- saltstack/hortonworks/pillar/java/init.sls
- scripts/salt-install.sh
CDPR-31 Fix firewall os condition
CDPR-29 Only install headless and devel java packages for redhat7
CDPR-25 Move storage increasing to salt states
CDPR-24 Move yum config fix to salt states
> CDPR-7 RHEL based image burning improvements

- saltstack/base/salt/prerequisites/usr/bin/user-data-helper.sh
Refactor proxy config as CCMV2 setup will not run on other hosts.
> CB-13483 Start CCMv2 Jumpgate agent on FreeIPA host only

- packer.json
- saltstack/base/salt/ccmv2/init.sls
- scripts/packer.sh
Provide jumpgate agent rpm url as an input parameter.
> CDPR-16: Provide jumpgate agent rpm url as an input parameter

- saltstack/base/salt/ccmv2/init.sls
- saltstack/base/salt/prerequisites/init.sls
- saltstack/base/salt/prerequisites/path.sls
- saltstack/freeipa/salt/freeipa/init.sls
- scripts/salt-install.sh
CDPR-44 Handle existing exclude directive in /etc/yum.conf
CDPR-43 Add sbin directories to path if they are not present
CDPR-42 Enable rhscl repo if not already enabled
CDPR-40 CDPR-41 Skip gpgchecks
> RHEL fixes

- packer.json
- saltstack/final/salt/cleanup/tmp/generate-package-versions.sh
Version numbers for the below packages are introduced in package version section of catalog:
* Metering agent (cb relevant image)
* FreeIPA plugin (freeipa)
* FreeIPA health agent (freeipa)
> CDPR-46: Version numbers missing from the image catalog

- Makefile
- scripts/salt-setup.sh
Besides being annoying when viewed as clear text or pasted into Jira tickets those simply inflated the logs for no reason.
> Removed ANSI color codes from the output

- saltstack/hortonworks/salt/pre-warm/cm.sls
> CB-15751 - Remove CM DB package

- Makefile
- packer.json
- scripts/generate-delta-package-list.sh
Not just the delta package list required but also the full list where we can find the OS relevant packages too.
> CB-15989: Store the full package list besides the delta

- saltstack/base/salt/postgresql/init.sls
Can only be merged after https://github.com/hortonworks/cloudbreak/pull/12235 reaches prod to avoid issues
> CB-15128 Set nologin shell for postgresql

- saltstack/base/salt/ccmv2/cdp/bin/ccmv2/generate-config.sh
- saltstack/base/salt/ccmv2/etc/logrotate.d/ccmv2
- saltstack/base/salt/prerequisites/usr/bin/ccmv2-helper.sh
- saltstack/base/salt/prerequisites/usr/bin/user-data-helper.sh
Refactor CCMV2 setup into a helper script. It will be used for CCM migration.
> CB-16679 Fix Jumpgate log's ownership and logrotate entry

- saltstack/final/salt/cis-controls/init.sls
This reverts commit d3fd6683ec968668cbf6e084750df00270ebefbd.
> Revert "CB-16938 Revert 'CIS: Strengthen the password policy'"

- Makefile
- scripts/get-salt-version.sh
Salt version updated to 3004.1
> CB-16854: Update salt to version 3004.1

- scripts/get-salt-version.sh
Revert salt version, we should use 3000.8
> CB-16854: Revert the new salt version to 3000.8

- Makefile
Publish feature was implemented for changelog generation.
> CB-18764: Publish the generated changelog file

- scripts/aws-copy.sh
After copying the image, we need to check the status of the image in order to give feedback to the jenkins job.
> CB-19843 - Images not published in ap-east-1 region (Hong Kong)

- scripts/aws-copy.sh
The validator functions were running in background and the return value of these tasks have no affect on the main task. With this correction the jobs's return values will be checked and handled.
> CB-20415: Image copy fails but the jenkins job is green

- saltstack/base/salt/salt/etc/salt/minion.d/custom.conf
This PR is due to the following escalation: ENGESC-14373
> CB-17072 - increase the salt retry count upon unsuccessful attempt

- Makefile
This PR updates the Jumpgate agent version from 3.0.2 to 3.0.3 for our new release.
> CDPAM-3759| Update jumpgate agent version

- Makefile
- scripts/packer.sh
- scripts/sparseimage/packer.sh
Test image validated successfully: http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-awsgov/75/
> CB-21449 Update Packer version for AWS GOV image burning

- Makefile
- saltstack/hortonworks/salt/java/init.sls
- scripts/sparseimage/packer.json
Note: review this as it was a single commit - not sure what kind of magic happened with Git during the last push, but Git insisted on pulling the remote branch into the local before pushing although there were zero differences and so it created an empty merge commit... Yep, magic.
> CB-21718: Install OpenJDK 17 on CentOS 7

- saltstack/final/salt/cis-controls/init.sls
Validated with Azure freeipa and runtime images:
http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-azure/2482/
http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-azure/2495/
> CB-21585 CIS: Mask rpcbind service

- saltstack/base/salt/prerequisites/usr/bin/user-data-helper.sh
Validated image: http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-azure/2531/
```
[cloudbreak@azure-test-f23a44f9-idbroker0 ~]$ lsblk
NAME              MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda                 8:0    0  100G  0 disk 
|-sda1              8:1    0  500M  0 part /boot
|-sda2              8:2    0   99G  0 part 
| |-rootvg-tmplv  253:0    0   12G  0 lvm  /tmp
| |-rootvg-usrlv  253:1    0   10G  0 lvm  /usr
| |-rootvg-homelv 253:2    0    1G  0 lvm  /home
| |-rootvg-varlv  253:3    0   12G  0 lvm  /var
| `-rootvg-rootlv 253:4    0   64G  0 lvm  /
|-sda14             8:14   0    4M  0 part 
`-sda15             8:15   0  495M  0 part /boot/efi
sdb                 8:16   0  400G  0 disk 
`-sdb1              8:17   0  400G  0 part /mnt
sdc                 8:32   0 …
```
> CB-22153 Resize partitions to full disk on Redhat 8

- saltstack/hortonworks/salt/java/init.sls
Test build: /job/cloudbreak-multi-packer-image-builder-salt-v3/1629/console
> CB-22564: Disabled default keystore type for FIPS

- saltstack/base/salt/prerequisites/repository.sls
- saltstack/final/salt/cis-controls/init.sls
Latest report created from test image: https://docs.google.com/spreadsheets/d/1FcE7ZScqex6sdJEXZd27ha89MplaLtewmh1s3G9Johc/edit#gid=1644478174
> CB-8896 CIS

- scripts/packer.sh
```
[root@ip-10-112-6-106 cloudbreak]# dnf list | grep cdp-
cdp-logging-agent.x86_64                               1.2.6_b53_redhat8-1                                         @System                        
cdp-minifi-agent.x86_64                                1.22.07-1                                                   @System                        
cdp-request-signer.x86_64                              0.2.4-1                                                     @System                        
cdp-telemetry.x86_64                                   0.4.36-1                                                    @System 
```
> CB-22421 Override cdp-infra-tools urls for redhat8

- saltstack/base/salt/postgresql/yum/postgres10-el6.repo
- saltstack/base/salt/postgresql/yum/postgres10-el7.repo
Validation passed: http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-aws/3033/
> CB-23115 Use the official postgresql yum archive for PG10

- Makefile
- scripts/changelog/collect-package-changelogs.sh
- scripts/changelog/packer.json
Package changelog generation needs to be updated for RHEL8
> CB-23098: Update the changelog generator to work with RHEL8

- saltstack/base/salt/postgresql/init.sls
- saltstack/final/salt/metadata/tmp/generate-package-versions.sh
- scripts/salt-install.sh
Test build: /job/cloudbreak-multi-packer-image-builder-salt-v3/2343/
> CB-23232: Added Python 3.9 for RHEL8 + RT 7.2.18 combo

- saltstack/final/salt/cleanup/kernel.sls
Test build in progress: /job/cloudbreak-multi-packer-image-builder-salt-v3/2397/
> CB-23357: Added old kernel removal for RHEL8

- saltstack/base/salt/nginx/init.sls
Test build: /job/cloudbreak-multi-packer-image-builder-salt-v3/2539/
Test validation: /job/api-e2e-imagevalidator-aws/3092/
> ENGESC-22007: Upgrade nginx to 1.20.x

- Makefile
- docker/redhat8/Dockerfile
- docker/redhat8/LICENSE
- docker/redhat8/README.md
- docker/redhat8/image-runtime-scripts/start-services-script.sh
- saltstack/base/salt/prerequisites/corkscrew.sls
- saltstack/base/salt/prerequisites/firewall.sls
- scripts/salt-install.sh
Support RHEL8 images on YCloud.
> CB-23015 : Get RHEL8 source image for YCloud

- saltstack/base/salt/prerequisites/packages.sls
http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-aws/3163
> CB-23559 Remove insights-client package on RHEL8

- saltstack/base/salt/postgresql/init.sls
This reverts commit 2741c35c86c5fcb73e1d0a154f4d987afe360d77.
http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-aws/3164
> Revert "trying to workaround postgres install issues"

- docker/centos7.9/Dockerfile
http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/3100/
> CB-23955 Bump centos7 yarn source image version

- scripts/salt-install.sh
http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-azure/3000/
> CB-23077 Fix mirror.infra.cloudera.com IP lookup and hosts append

- saltstack/base/salt/postgresql/init.sls
Test build http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/3663/
> CB-24649: Different implementation of preventing PG autostart on VMs

- docker/centos7.9/Dockerfile
- docker/redhat8/Dockerfile
CentOS7: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/3804/
RHEL8: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/3802/
> CB-25039 Remove hwx-internal.repo at the end of YARN image burning

- saltstack/hortonworks/salt/pre-warm/tmp/pre_warm_parcels.py
http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/4289/
```
[cloudbreak@ip-10-84-199-74 ~]$ ls -la /opt/cloudera/parcel-repo
total 428
drwxr-xr-x. 2 cloudera-scm cloudera-scm   4096 Apr 24 12:06 .
drwxr-xr-x. 8 cloudera-scm cloudera-scm     97 Apr 24 11:57 ..
-rw-r--r--. 2 cloudera-scm cloudera-scm      0 Apr 24 12:02 CDH-7.2.17-1.cdh7.2.17.p400.52424530-el8.parcel
-rw-r--r--. 1 cloudera-scm cloudera-scm     40 Apr 24 12:00 CDH-7.2.17-1.cdh7.2.17.p400.52424530-el8.parcel.sha
-rw-r--r--. 1 cloudera-scm cloudera-scm      0 Apr 24 12:02 CDH-7.2.17-1.cdh7.2.17.p400.52424530-el8.parcel.skiphash
-rw-r--r--. 1 cloudera-scm cloudera-scm 403126 Apr 24 12:02 CDH-7.2.17-1.cdh7.2.17.p400.52424530-el8.parcel.torrent
-rw-r--r--. 1 cloudera-scm cloudera-scm      0 Apr 24 …
```
> CB-25565 Place .sha next to prewarm parcels

- saltstack/final/salt/hue-hack/init.sls
- saltstack/final/salt/metadata/tmp/generate-package-versions.sh
Test build: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/4553/
> CB-25753 and CB-26055: See commit messages for details

- saltstack/base/salt/nginx/init.sls
Test build: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/4584/
> CB-26166: Bumped Nginx version

- scripts/salt-install.sh
A little more explanation for this delete-heavy commit:
- RHEL 7 is pretty much dead, so is the related code.
- Even a year ago we've supported many different runtime/OS combinations which required us to branch the logic and install different Python versions on different images. On top of that, we've tried to be future proof whenever we could, adding redundant Python versions "just in case" and whatnot. Eventually this whole thing became a (non-flying) Spaghetti Monster. Now with most pre-7.2.16 runtimes and RHEL 7 gone, plus that we know that no major development will be done (if any at all) for CentOS7, finally we could clean this up.
**Test builds:**
AWS 7.2.16 CentOS 7 - http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/4666/ - ✅ 
GOV 7.2.18 RHEL 8 - …
> CB-26229: Cleaned up Python installation mess, dropped RHEL 7 support

- Makefile
- README.image-content.md
- packer.json
- saltstack/base/salt/monitoring/blackbox-exporter.sls
- saltstack/base/salt/monitoring/cdp-prometheus.sls
- saltstack/base/salt/monitoring/node-exporter.sls
- saltstack/base/salt/postgresql/init.sls
- saltstack/base/salt/postgresql/yum/postgres11-el8.repo
- saltstack/base/salt/prerequisites/cert-tool.sls
- saltstack/base/salt/prerequisites/packages.sls
- saltstack/base/salt/prerequisites/pip.sls
- saltstack/base/salt/prerequisites/usr/bin/user-data-helper.sh
- saltstack/base/salt/salt-bootstrap/init.sls
- saltstack/final/salt/cis-controls/common.sls
- saltstack/final/salt/cleanup/kernel.sls
- saltstack/hortonworks/salt/java/init.sls
- scripts/hardcoded-packages.csv
- scripts/packer.sh
- scripts/pp_json.sh
- scripts/salt-install.sh
arm64: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/4667/
x86_64: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/4668/
> CB-26215 Burning ARM based AWS images

- Makefile
- docker/redhat8/Dockerfile
The custom freeIPA images were built with the new version of jumpgate agent and published. The information can be found here
https://github.com/hortonworks/cloudbreak-images/tree/jumpgate-artifact/jumpgate. UUIDs for the images are below:
* AWS - "9e08387a-6773-4581-b7f6-5362be206eb4"
* Azure - "7002f77b-148b-4da8-bde0-a7c49bf9d0a3"
* GCP - "ece48199-7e39-470d-9065-7dfd97371a19"
E2E tests were run with the custom freeIPA images and the tests were successful. Refer https://quanta.infra.cloudera.com/#/runDetails?gtn=54656556
AWS test run
```
{
"environmentName": "e2e-54656556-315-env",
"credentialName": "cdpe2e-credential-aws-manowar-e2etest",
"region": "us-west-2",
"vpcId": "vpc-0c55644ba799825a2",
"subnetIds": [
"subnet-05bbb3a6c02d0a76a",
"subnet-0ac6a804221711fc2", …
```
> CDPAM-4949 | Update jumpgate agent to 3.0.9 in freeIPA image

- scripts/salt-install.sh
CB-26511 Remove static /etc/hosts entry for mirror.infra.cloudera.com from base images
> CB-26511 Remove static /etc/hosts entry for mirror.infra.cloudera.com

- saltstack/base/salt/prerequisites/packages.sls
- saltstack/hortonworks/salt/java/init.sls
- scripts/salt-install.sh
http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/4953
> CB-26533 All mirror repos are available for RHEL 8.8 arm64

- saltstack/hortonworks/salt/java/init.sls
Test build: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/5111/
> CB-25097: Remove hardcoded version numbers from RHEL 8 repo URLs

- saltstack/base/salt/prerequisites/init.sls
- saltstack/base/salt/prerequisites/packages.sls
- saltstack/base/salt/prerequisites/setroubleshoot.sls
Test build: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/5110/
> CB-24945 RHEL 8.10 Azure fixes

- Makefile
- packer.json
- saltstack/base/salt/prerequisites/init.sls
- saltstack/base/salt/prerequisites/setroubleshoot.sls
- saltstack/final/salt/cis-controls/common.sls
- saltstack/final/salt/metadata/tmp/generate-package-versions.sh
- saltstack/hortonworks/salt/java/init.sls
- scripts/salt-final.sh
- scripts/salt-setup.sh
Test images:
- RHEL 8.10 + 7.3.1 - https://jira.cloudera.com/browse/PCRR-422
- RHEL 8.10 + FreeIPA - https://jira.cloudera.com/browse/PCRR-431
- RHEL 8.10 + Base - https://jira.cloudera.com/browse/CB-26802
> CB-24945: Support for RHEL 8.10

- saltstack/base/salt/luks/etc/systemd/system/cdp-reopen-luks-volume.service
> CB-25449: Add dependencies to the LUKS volume reopen service for services using the LUKS volume

- Makefile
- scripts/changelog/packer.json
- scripts/changelog/packer.sh
Azure rhel8 Freeipa changelog creation failed with VMMarketplaceInvalidInput error.
> CB-27450: Fix VMMarketplaceInvalidInput issue during changelog generation

- Makefile
- docker/redhat8/Dockerfile
The custom freeIPA images were built with the new version of jumpgate agent and published. The information can be found here
https://github.com/hortonworks/cloudbreak-images/tree/jumpgate-artifact/jumpgate. UUIDs for the images are below:
AWS - "840b1e60-f992-4d75-87ec-adf6d120b549"
Azure - "33039d91-9383-46d7-b72e-a5d8563bdb25"
GCP - "7ae28891-51ac-4b53-a774-ea514f0c7ec9"
E2E tests were run with the custom freeIPA images and the tests were successful. Refer 
`https://quanta.infra.cloudera.com/?#/runDetails?gtn=54656556`
AWS
`{
"environmentName": "e2e-58848781-438-env",
"credentialName": "cdpe2e-credential-aws-manowar-e2etest",
"region": "us-west-2",
"vpcId": "vpc-0c55644ba799825a2",
"subnetIds": [
"subnet-05bbb3a6c02d0a76a",
"subnet-0ac6a804221711fc2",
"subnet-0ee2ba7b5bb2fcc29"
], …
> Update jumpgate agent to 3.8.0 in freeIPA image

- saltstack/base/salt/top.sls
Test build: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/5824/
Successful validation: http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-v2/1740/
> CB-26310: Removed PostgreSQL installation from FreeIPA images

- scripts/repo_cleanup.sh
Test build: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/5823/
Successful validation: http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-v2/1741/
> CB-27371: Remove unnecessary PG repo file from images

- saltstack/final/salt/cis-controls/scripts/cis_control.sh
- scripts/get-image-size.sh
Test build: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/5831/
> CB-27689: Fix failing Ansible installation in case of GCP (RHEL8 CIS)

- saltstack/base/salt/hostname/init.sls
- saltstack/base/salt/top.sls
- saltstack/final/salt/hacks-and-tweaks/init.sls
http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/5857/console
> CB-27774 Remove GCP hostname override script

- scripts/push-to-metadata-repo.sh
CB-28063 Try rebasing before updating image metadata repo to avoid git push concurrency issues
> CB-28063 Try rebasing before updating image metadata repo

- saltstack/base/salt/prerequisites/packages.sls
- saltstack/base/salt/selinux/etc/selinux/cdp/hostname_policy.te
- saltstack/base/salt/selinux/etc/selinux/cdp/install-hostname-policy.sh
- saltstack/base/salt/selinux/init.sls
- saltstack/base/salt/top.sls
Successful validator runs for this change:
- FreeIPA: http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-v2/2073/
- Prewarmed: http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-v2/2074/
> CB-28097: Add hostname file SELinux policy

- saltstack/base/salt/prerequisites/usr/bin/user-data-helper.sh
image burning:
runtime: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/6337/console
freeipa: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/6331/consoleFull
validation run:
runtime: http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-v2/2239/console
freeipa: http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-v2/2236/console
> CB-27537 Low storage allocation for the home directory on COD cluster on Azure

- saltstack/base/salt/prerequisites/disable_ipv6.sls
- saltstack/base/salt/prerequisites/etc/cloud/cloud.cfg.d/99-disable-ipv6.cfg
image burning: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/6347/console
validation: http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-v2/2262/
> ENGESC-27912 Disable DHCPV6C

- saltstack/base/salt/prerequisites/packages.sls
- saltstack/hortonworks/salt/kerberos/ad.sls
- saltstack/hortonworks/salt/kerberos/init.sls
Reverts hortonworks/cloudbreak-images#1115
> Revert "CB-28374 Add AD related packages to image"

- saltstack/base/salt/prerequisites/packages.sls
- saltstack/hortonworks/salt/kerberos/ad.sls
- saltstack/hortonworks/salt/kerberos/init.sls
Also for ECS `iscsi-initiator-utils` is required.
> CB-28374 Add AD related packages to image

- saltstack/base/salt/telemetry/init.sls
- saltstack/base/salt/telemetry/yum/cdp-infra-tools.repo.j2
Test image burning: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/6602/console
> CB-28784: Restricted cdp-infra-tools to v1.3.5_b1

- Makefile
- scripts/packer.sh
Test build - FreeIPA - http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/6628/console
Test build - Runtime - http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/6629/console
> CB-28783: Change gov proxy to be only used from within AWS Gov instances

- saltstack/base/salt/postgresql/init.sls
Test builds:
- RHEL8 AWS 7.2.17 (should not install as it is RHEL 8.8) - http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/6841/ ✅ 
- RHEL8 AWS 7.2.18 (should install) - http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/6842/ ✅ 
- CentOS 7 AWS 7.2.17 (should not install) - http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/6836/ ✅ 
- RHEL8 YARN base (should install) - http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/6840/ ✅
> CB-29198: Install PostgreSQL 17 on images

- saltstack/final/salt/metadata/tmp/generate-package-versions.sh
- scripts/packer.sh
Test build: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/6875/
> CB-28556: Use arm64 packages for FreeIPA when needed

- scripts/packer.sh
Moving to latest release ARM build .
> CDPAM-6004: Pointing to Releng based ARM build 

- saltstack/base/salt/postgresql/init.sls
Reverts hortonworks/cloudbreak-images#1187
> Revert "CB-30176 Avoid installing PostgreSQL 11 on RHEL 9 images"

- Makefile
- docker/centos7.9/Dockerfile
- docker/redhat8.10/Dockerfile
- docker/redhat8/Dockerfile
- docker/yarn-loadbalancer/Dockerfile
- saltstack/final/salt/metadata/tmp/generate-package-versions.sh
- scripts/azure-copy.sh
- scripts/get-azure-vm-image-version.sh
- scripts/img-copy.sh
- scripts/packer.sh
migratig all RelEng and QAInfra services from *.infra.cloudera.com to *.eng.cloudera.com
> CB-30324 migrate all RelEng and QAInfra services from *.infra.cloudera.com to *.eng.cloudera.com

- packer.json
- saltstack/base/salt/prerequisites/oscap.sls
> Cb-30573 Create dummy oscap file

- saltstack/final/salt/openscap/init.sls
- azure: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/8692/console
- change is salt related, no need for other providers
- N\A, scan change only
- N\A, scan change only
- N\A, scan change only
- N\A, scan change only
- N\A, scan change only
> **Note:**  
> CB-30494 Fix CIS L1 scan for redhat9

- saltstack/base/salt/telemetry/init.sls
> CB-30546: Fixed missing cdp-request-signer on RHEL 9

- packer.json
- saltstack/base/salt/selinux/init.sls
> CB-30635: Fix SELinux log permissions
