hortonworks/cloudbreak-images

Vagrantfile
repos/salt-repo-2016.11-6.el.repo
repos/salt-repo-2017.7.el.repo
saltstack/base/salt/top.sls

New repo contains newer python urllib3 which contains the backported ssl_match_hostname module.

Fix requests module import problems on centos6

---

saltstack/base/salt/resolvconf/etc/resolvconf/update.d/unbound
saltstack/base/salt/resolvconf/etc/systemd/system/resolvconf.service
saltstack/base/salt/resolvconf/init.sls
saltstack/base/salt/top.sls

On Ubuntu16 resolvconf package manages /etc/resolv.conf, therefore dhcp-client generated unbound configuration is not accessible. Ambari-agent connects ambari-server by domain name which fails since name resolution is misconfigured.

Manage unbound with resolvconf on Debian/Ubuntu

---

saltstack/base/salt/postgresql/scripts/conf_pgsql_listen_address.sh

During 'docker build' a fake systemd exists and services are not started.
That is why we are not able to query postgresql to the location of its
configuration file.

Fix how to locate postgres.conf on docker containers

---

docker/common/start-systemd.sh
docker/common/systemd-fix.service
docker/debian9/Dockerfile
docker/ubuntu16/Dockerfile
saltstack/base/salt/cloud-init/init.sls
saltstack/base/salt/prerequisites/repository.sls
saltstack/base/salt/top.sls
saltstack/base/salt/unbound/init.sls
saltstack/final/salt/cleanup/salt.sls

* Redirect all name resolution requests to locally configured unbound
daemon and set up nameservers in its configuration
* SSH login problem fix for "System is booting up. See pam_nologin(8)"
messages
* Parameter handling (user-data) through /etc/cloudbreak-config.props
* Mofidy CMD to /bootstrap/start-systemd as it is hardwired into
CloudBreak
* Create /run/systemd/system directory runtime because Type=notify
services did not work when it was missing
* Clear /var/cache/salt/minion directory at the end of image creation
* Fix salt-api authentication problem when running in a container
Closes-Bug: SUST-618, SUST-619

Fix docker build for debian9 and ubuntu16

---

Makefile
saltstack/final/salt/cleanup/tmp/generate-package-versions.sh

For now I have hard coded salt-bootstrap and salt version to be part of the json and removed python and kernel since it does not work on some distributions. Package names are varying on distros
python -> python27
kernel -> linux-images etc..
For now we're not including this information in the catalog
Also changed the json construction to be done with jq

Pkgversionfix

---

saltstack/base/salt/monitoring/consul-template.sls
saltstack/base/salt/monitoring/consul.sls
saltstack/base/salt/monitoring/service-registration.sls
saltstack/base/salt/prerequisites/pip.sls
saltstack/base/salt/salt-bootstrap/init.sls
saltstack/optional/salt/mysql-jdbc-driver/init.sls

Validated end-to-end with RHEL7 and CentOS 7.

Added missing hash values for third party dependencies.

---

saltstack/base/salt/custom/usr/local/bin/custom-ansible.sh
saltstack/base/salt/custom/usr/local/bin/custom-puppet.sh

Attached examples show integration of both Ansible Playbooks and Puppet during custom AMI generation process.  Just rename the file custom.sh and adjust Git to run external OS hardening processes.

Ansible Playbooks & Puppet Modules Integration

---

saltstack/hortonworks/salt/fluent/init.sls

use cldr public gem repo, as fluent-plugin-databus is available there, the repo is not configurable yet so it's passed as a constant
similar as: https://github.com/hortonworks/cloudbreak/pull/5478
i did not test this code, only the change on the PR above, but that is exactly the same

CB-2140. Use cloudera public gem repo for install fluent-plugin-databus.

---

saltstack/base/salt/ccm-client/cdp/bin/reverse-tunnel-values.sh
saltstack/base/salt/ccm-client/cdp/bin/reverse-tunnel.sh
saltstack/base/salt/ccm-client/cdp/bin/update-reverse-tunnel-values.sh
saltstack/base/salt/ccm-client/init.sls
saltstack/base/salt/ccm-client/systemd/tunnel@.service
saltstack/base/salt/prerequisites/packages.sls
saltstack/base/salt/top.sls

With these changes, the CCM client infrastructure and prerequisites
have been added to the Salt configuration for CB images.

CLOUD-2066. Add CCM client to CB images.

---

saltstack/hortonworks/salt/metering/init.sls

With a newer version of the metering application, the rpm will install only a binary and won't depend on any python/pip libs

Update metering package to use binary package (instead of install python pip deps)

---

saltstack/base/salt/ccm-client/cdp/bin/update-reverse-tunnel-values.sh
saltstack/base/salt/prerequisites/usr/bin/user-data-helper.sh

With these changes, the CCM variables are correctly passed through
to the update script, and the provider-specific instance ID is used
as the default CCM tunnel initiator ID.

CB-2654. Additional script improvements.

---

scripts/pp_json.sh

see https://github.com/hortonworks/cloudbreak-images/pull/328

fix {image_name}.json generation for base images (no pre-warm parcels)

---

saltstack/base/salt/nginx/etc/nginx/nginx.conf

Nginx by default prevents underscores in header names.
The HTTP spec allows underscores in headers. This change
configures Nginx to allow underscores in headers. It needs
to be configured at the top level since there are multiple
Nginx server config blocks.
http://nginx.org/en/docs/http/ngx_http_core_module.html#underscores_in_headers
Some additional background on underscores in headers can
be found here:
https://stackoverflow.com/questions/22856136/why-http-servers-forbid-underscores-in-http-header-names
Signed-off-by: Kevin Risden <krisden@apache.org>

CB-4366 Nginx should allow underscores in header names

---

saltstack/base/salt/prerequisites/usr/bin/user-data-helper.sh

Reverts hortonworks/cloudbreak-images#355

Revert "CB-4307 Skip 2-way-ssl setup when reverse tunnel is used"

---

saltstack/base/salt/prerequisites/sysctl.sls

add new system defaults
build tested, image build successfully finished
testing against cluster creation - done, looked good.

CB-4947. Better OS defaults for azure/aws nodes.

---

saltstack/base/salt/monitoring/jmx-exporter.sls
saltstack/base/salt/monitoring/prometheus.sls

tested with `build-aws-centos7` make target (base image):
╭─ahorvath~
╰─$ docker logs e963e533cdbd | grep "ID: /opt/jmx_javaagent.jar" -A 12
aws-centos7:           ID: /opt/jmx_javaagent.jar
aws-centos7:     Function: file.managed
aws-centos7:       Result: True
aws-centos7:      Comment: File /opt/jmx_javaagent.jar updated
aws-centos7:      Started: 08:49:07.378811
aws-centos7:     Duration: 34.247 ms
aws-centos7:      Changes:
aws-centos7:               ----------
aws-centos7:               diff:
aws-centos7:                   New file
aws-centos7:               mode:
aws-centos7:                   0644
aws-centos7: ----------
╭─ahorvath~
╰─$ docker logs e963e533cdbd | grep "ID: install_jmx_javaagent_exporter" -A 8
aws-centos7:           ID: install_jmx_javaagent_exporter
aws-centos7: …

CB-5138 image burning fails while it tries to download jmx_javaagent

---

scripts/salt-install.sh

failed: http://build.eng.hortonworks.com:8080/job/cloudbreak-multi-packer-image-builder-salt-v3/365/console
working build started with the feature branch of this PR: http://build.eng.hortonworks.com:8080/job/cloudbreak-multi-packer-image-builder-salt-v3/366/console

Upgrade pip to overcome zipp issue

---

saltstack/base/salt/prerequisites/packages.sls
saltstack/freeipa/salt/freeipa/init.sls

This is adding the AWS CLI tools and AZCopy to the FreeIPA image creation in order to support automatic backups of the FreeIPA service to cloud-based object stores.  It was not added to the general image due to the specific nature of adding the AZcopy binary and wanting to limit the impact of the AWS CLI on other images builds.
Closes #CB-5338
Closes #CB-5337

CB-5334 Changes for FreeIPA backup

---

saltstack/base/salt/prerequisites/init.sls
saltstack/base/salt/prerequisites/jinja.sls

I tried pip.installed, but I couldn't make it work when virtualenv is used. You can specify bin_env, but didn't work either.

CB-6032 add jinja2 package to global python rather than virtualenv

---

saltstack/freeipa/salt/freeipa/init.sls

Update the FreeIPA plugin to fix 2 issues with the user password sync.
This was tested by creating the AMI and checking the checksum of the
FreeIPA plugin's shared library.

CB-6080 & CDPSDX-1621: Fix CDP password user sync

---

Makefile
scripts/salt-install.sh
scripts/salt-setup.sh
scripts/salt_requirements.txt

I had better results with 7.7 than 7.5 and it does not require backend changes so I think we should upgrade to this version.

update to saltstack 2017.7.7

---

saltstack/hortonworks/salt/java/init.sls

Our nodes won't start without this fix: 
```++ keytool -importkeystore -srckeystore /usr/lib/jvm/java/jre/lib/security/cacerts -srcstorepass changeit -destkeystore /opt/cacerts/cacerts.p12 -deststorepass changeit -deststoretype PKCS12
Importing keystore /usr/lib/jvm/java/jre/lib/security/cacerts to /opt/cacerts/cacerts.p12...
keytool error: java.io.FileNotFoundException: /usr/lib/jvm/java/jre/lib/security/cacerts (No such file or directory)```

FIX: Java 11 missing symlink

---

saltstack/base/salt/prerequisites/pip.sls

this 3rd parties will be required to be installed if we will use filecollector lib for log collection.
the development of filecollector usage is in progress, but the it's ok to these 3rd parties on the image

CB-7750. install 3rd party libs for filecollector

---

saltstack/base/salt/salt-bootstrap/etc/systemd/system/salt-bootstrap.service

This commit modifies the systemd unit file belonging to
salt-bootstrap.
It will switch from `on-failure` to `always` as we experienced that
the process is killed accidentally by end users.
For more information regarding the `Restart` directive please see:
https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=

CB-7811 salt-boostrap restart directive should be 'always'

---

saltstack/base/salt/fluent/init.sls

update databus version -  there is a new field that can supprt to pass dynamic header fields for databus, for example: append some dynamic fields to kibana during file collection (which does not come from a static file, filecollector streams data to fluentd) 
to not need to re-build freeipa image yet. if it's built that's fine, the CB check on databus version only will update the gem if the value is lower (not higher)

CB-7877. Update databus version for CB images (to support dynamic headers)

---

saltstack/base/salt/ccm-client/cdp/bin/reverse-tunnel.sh

Autossh process relies on the underlying SSH command to fail
after 1,5 minutes (30 * 3 sec) and restarts the tunnel upon such
connection failure. However if you cut the circuit towards to
the LB and the SSH command is not able to re-connect to the server
it just hangs. If it hangs autossh will not be able to detect the
failure as the SSH command is live, but does not do anything and
all extra monitoring is disabled with M 0. If we introduce the
ConnectTimeout option to the SSH command it will not hang, but fail
after the given time in seconds and autossh will be able to restart
the command.

CB-7813 add ConnectTimeout parameter to auto ssh command

---

packer.json

CB-7348 Update AWS AMI to the latest Centos7 AMI
The following script was used to determine the AMI:
```
aws ec2 describe-images \                                                   
--owners aws-marketplace \
--filters '[
{"Name": "name",                "Values": ["CentOS Linux 7*"]},
{"Name": "virtualization-type", "Values": ["hvm"]},
{"Name": "architecture",        "Values": ["x86_64"]},
{"Name": "image-type",          "Values": ["machine"]}
]' \
--query 'sort_by(Images, &CreationDate)[-1]' \
--region us-west-1 \
--output json
```

CB-7348 Update AWS AMI to the latest Centos7 AMI

---

saltstack/base/salt/telemetry/init.sls
saltstack/base/salt/top.sls

it should install https://cloudera-service-delivery-cache.s3.amazonaws.com/telemetry/cdp-telemetry/cdp_telemetry-0.1.0.x86_64.rpm to base images

CB-8160. Install CDP telemetry cli

---

saltstack/freeipa/salt/freeipa/init.sls

This updates the FreeIPA health agent RPM to the latest working
version.

CB-8354: Update FreeIPA image with new fixed FreeIPA health agent

---

saltstack/base/salt/salt/etc/salt/master.d/custom.conf

As the code which handles fingerprint matching and accepting minions reached prod
we can safely remove autojoin
tested:
- created image from local
- from the new image distrox provisioned
- upscale
- downscale

CB-7988 Remove auto join from salt master configuration

---

saltstack/base/salt/prerequisites/httpd.sls
saltstack/base/salt/prerequisites/init.sls

New httpd salt file is added to the prerequisites which removes the previously installed httpd and installs it again from a specified repository.

CB-8529: Starting Hue fails with longer stackname and 7.1.0 DE template

---

saltstack/freeipa/salt/freeipa/init.sls

Update the CDP health agent for FreeIPA to have improved health status
for the various plugins.

CB-8662: Update the CDP health agent for FreeIPA

---

saltstack/hortonworks/salt/pre-warm/tmp/install_cdh.sh

KEYTRUSTEE_SERVER is available with sha checksum what was not supported before.
http://cloudera-build-us-west-1.vpc.cloudera.com/s3/build/6656988/cdh/7.x/parcels/
Adding support to validate sha checksums when burning a prewarmed image.

CB-9459 Adds sha checksum support to validate KEYTRUSTEE_SERVER parcel.

---

saltstack/base/salt/nginx/etc/nginx/ssl.conf
saltstack/base/salt/prerequisites/usr/bin/user-data-helper.sh
saltstack/base/salt/salt/etc/salt/master.d/custom.conf
scripts/salt_requirements.txt

This commit:
- adds PyOpenSSL as a requirement for salt pip install
- add cert generation to `user-data-helper` script for salt-api
- turns on SSL for salt-api
- changes nginx configuration to use salt-api via SSL
Depends on: https://github.com/hortonworks/cloudbreak/pull/8922
This change is not backward compatible with older CB versions.
**Wait for CB 2.30 to reach prod**

CB-8414 Enable SSL on Salt-API (rest_cherrypy)

---

Vagrantfile
docker/centos7.3/Dockerfile
docker/centos7.3/files/image-runtime-scripts/start-services-script.sh
docker/centos7.4/image-runtime-scripts/start-services-script.sh
docker/centos7.5/image-runtime-scripts/start-services-script.sh
docker/centos7.6/image-runtime-scripts/start-services-script.sh
saltstack/base/salt/prerequisites/packages.sls

The support of centos6 reached the end of life, therefore it should be removed from the salt stack.

CB-9814: Remove the centos6 support from the salt stack of images repository

---

saltstack/base/salt/cis-controls/init.sls

Update to address below build failed error.
http://build.eng.hortonworks.com:8080/job/cloudbreak-multi-packer-image-builder-salt-v3/2052/
http://build.eng.hortonworks.com:8080/job/cloudbreak-multi-packer-image-builder-salt-v3/2053/
http://build.eng.hortonworks.com:8080/job/cloudbreak-multi-packer-image-builder-salt-v3/2054/

CB-8897: Update to initial PR https://github.com/hortonworks/cloudbreak-images/pull/454

---

saltstack/base/salt/top.sls

This will make sure cis-hardening controls are runs as default.

Making the CIS-Benchmark controls as default

---

saltstack/base/salt/fluent/init.sls

details:
that is only used if salt does not override the sample configuration.
this can happen if not telemetry/logging is filled in the requests

CB-10040. Remove port usage of 8888 from cdp-logging-agent.conf sample

---

saltstack/base/salt/prerequisites/sysctl.sls

1. In other Clouds this value is by default set to zero, which means overcommit based on heuristics.
2. In GCP we take a default Centos image from that cloud which already has a setting of 1, which means enable overcommit.
3. This commit brings GCP to the baseline of what we have in other clouds.

CB-9982 Explicitly disable VM memory overcommit setting

---

saltstack/base/salt/top.sls

This reverts commit 6ab18da5a8f8053cfb3bbe69003915b4860496e4 as it breaks GCP and Azure image bakings

Revert "Making the CIS-Benchmark controls as default"

---

saltstack/base/salt/cis-controls/init.sls

Addressed the cause of beneath failed CB image builds.
http://build.eng.hortonworks.com:8080/job/cloudbreak-multi-packer-image-builder-salt-v3/2077/
http://build.eng.hortonworks.com:8080/job/cloudbreak-multi-packer-image-builder-salt-v3/2078/

CB-8897:CIS-Disable filesystems that aren't needed

---

saltstack/base/salt/cis-controls/init.sls
saltstack/base/salt/top.sls

Have addressed the cause of below failed builds. These controls can be default now.
http://build.eng.hortonworks.com:8080/job/cloudbreak-multi-packer-image-builder-salt-v3/2077/
http://build.eng.hortonworks.com:8080/job/cloudbreak-multi-packer-image-builder-salt-v3/2078/

CIS Controls as defaults

---

saltstack/base/salt/prerequisites/init.sls
saltstack/base/salt/prerequisites/user_uid.sls
scripts/salt-setup.sh

This PR implements 2 things:
1, creates static grain called builder_type based on env var PACKER_BUILDER_TYPE to be able to distinguish between cloud platform builds
2, populates ids jinja dictionary with the correct platform-specific uid and gid of cloudera-scm
Test:
Burnt non-default image with id 0edf9095-e87f-4f9e-8b32-066e2af1ca2e in dev catalog, validated with SDX and Data Hub launch.

CB-10271 - cloudera-scm user needs to be managed outside of CM

---

saltstack/base/salt/cis-controls/init.sls

By default the SSH LogLevel is set as INFO. It was flagged by aws inspector since the parameter was commented out in current sshd config file.

CB-8933:CIS-SSH Harden-Setting LogLevel as INFO

---

saltstack/base/salt/ccmv2-inverting-proxy-agent/cdp/bin/ccmv2/run-inverting-proxy-agent.sh
saltstack/base/salt/ccmv2-inverting-proxy-agent/cdp/bin/ccmv2/update-inverting-proxy-agent-values.sh
saltstack/base/salt/ccmv2-inverting-proxy-agent/etc/systemd/system/ccmv2-inverting-proxy-agent@.service
saltstack/base/salt/ccmv2-inverting-proxy-agent/init.sls
saltstack/base/salt/prerequisites/usr/bin/user-data-helper.sh
saltstack/base/salt/top.sls
saltstack/hortonworks/salt/ccmv2-inverting-proxy-agent/init.sls
saltstack/hortonworks/salt/top.sls

Salt stack is extended with install of ccmv2-inverting-proxy-agent.

CB-9183: [CCMv2] Make inverting proxy agent a part of ami/image

---

saltstack/base/salt/prerequisites/usr/bin/user-data-helper.sh

If CCMv2 is enabled while creating an environment, then ssl verify client parameter should be turned off and the nginx should listen in localhost:9443.

CB-10358: Changes to user-data-helper script to support one way TLS between inverting proxy agent and nginx

---

saltstack/base/salt/ccmv2-inverting-proxy-agent/cdp/bin/ccmv2/run-inverting-proxy-agent.sh

The logs are redirected to /var/log/ccmv2-inverting-proxy-agent.log

CB-10913: Inverting proxy agents are not writing logs into /var/log

---

saltstack/base/salt/cis-controls/init.sls
saltstack/base/salt/top.sls

Eliminating **SSH sshIdealTime** configuration due to e2e test failure for further investigation.

CB-8933: Harden SSH Configurations

---

saltstack/base/salt/cis-controls/init.sls
saltstack/base/salt/top.sls

There are 3 separate commits in this PR:
* Remove SSH ClientAlive timeout since @bormanbhaskar noticed it caused e2e test failures
** This was previously handled in https://github.com/hortonworks/cloudbreak-images/commit/fb48c04f78035f771ce21b7002e204ee106556bf
* Ensure udf filesystem is not disabled due to Azure needing it
** This could probably be split into Azure specifically with conditionals - but added as a comment for later
* Reenabled the CIS controls by default
** This is a separate commit so if necessary it can be reverted separately and not tied into any of the functionality changes
If/when this is merged - would be good to keep the separate commits instead of squashing them together if possible.

Improves CIS based on recent test failures

---

saltstack/base/salt/cis-controls/init.sls

This PR contains below updates:
1. CB-8926: Ensuring X-Window system is not installed
2. CB-8925: Restricting Core Dumps
The changes were tested for both aws and azure and the results can be seen below:
**AWS**
_http://build.eng.hortonworks.com:8080/job/cloudbreak-image-burn-salt-v3/14945/
http://build.eng.hortonworks.com:8080/job/cloudbreak-multi-packer-image-builder-salt-v3/2538/
http://build.eng.hortonworks.com:8080/job/imagecatalog-v3-append/1788/
http://ci-cloudbreak.eng.hortonworks.com/view/e2e-test/job/api-e2e-imagevalidator-aws/1056/_
**Azure**
_http://build.eng.hortonworks.com:8080/job/cloudbreak-image-burn-salt-v3/14946/
http://build.eng.hortonworks.com:8080/job/cloudbreak-multi-packer-image-builder-salt-v3/2540/
http://build.eng.hortonworks.com:8080/job/imagecatalog-v3-append/17 …

CB-8925, CB-8926: CIS hardening

---

saltstack/base/salt/cis-controls/init.sls

This PR enforces the below mentioned CIS controls onto CenttOSv7 base image.
- CB-8920
- CB-8932
- CB-8934
- CB-8935
The changes were validated for image burning and e2e test suites and all passed. Reference results are listed below:
**_AWS_**
1. http://build.eng.hortonworks.com:8080/job/cloudbreak-image-burn-salt-v3/15722/
2. http://build.eng.hortonworks.com:8080/job/cloudbreak-multi-packer-image-builder-salt-v3/2598/
3. http://build.eng.hortonworks.com:8080/job/imagecatalog-v3-append/1834/
4. http://ci-cloudbreak.eng.hortonworks.com/view/e2e-test/job/api-e2e-imagevalidator-aws/1075/
**_Azure_**
1. http://build.eng.hortonworks.com:8080/job/cloudbreak-image-burn-salt-v3/15723/
2. http://build.eng.hortonworks.com:8080/job/cloudbreak-multi-packer-image-builder-salt-v3/2599/
3. …

CIS: CB-8896 - Multiple checks

---

saltstack/base/salt/ccmv2-inverting-proxy-agent/init.sls

- Updated the GBN of the inverting proxy agent binary with the latest one.
- Updated the md5sum value of the latest agent binary file. `md5sum <path of the latest agent binary downloaded from RE portal>

CDPAM-1373 | update the URL for inverting proxy agent

---

saltstack/base/salt/ccmv2-inverting-proxy-agent/init.sls

The agent needs to support a way to conditionally skip validating the trust chain of the remote endpoint/backend. The actual change was done in inverting-proxy code.
This change updates the version of inverting-proxy being pulled into the AMIs.

CDPAM-1386: A way to optionally disable TLS verification in agent

---

saltstack/base/salt/ccm-client/cdp/bin/reverse-tunnel.sh

As part of [ENGESC-7388](https://jira.cloudera.com/browse/ENGESC-7388), we found that when storage is completely filled up on customer's cluster node and if autossh process gets restarted then the private key file gets corrupted and caused tunnel down downtime due to authentication failure which is not expected behavior. so As part of this PR, I am adding a check which would create a private key file only if it is not present and we can be safe from that restart scenario as on restart file would be already there.

CB-11684 | Do not create private key file if already present

---

Makefile

The manifest file that stores the package contents of images is uploaded to the github.

CB-11677: Upload image manifests to Github

---

saltstack/base/salt/prerequisites/sysctl.sls

The value of net.ipv4.tcp_retries2 is changed to 7 which is 15 by default earlier. Screenshots for the value before and after the change (tested with base ami bake):
Before:
Post the change:

CB-10822:Tune default value of net.ipv4.tcp_retries2 to 7 ootb for cdp clusters

---

saltstack/base/salt/ccmv2-inverting-proxy-agent/etc/logrotate/conf/ccmv2-inverting-proxy-agent
saltstack/base/salt/ccmv2-inverting-proxy-agent/init.sls

In this PR I have added a logrotate configuration file for ccmv2-inverting-proxy-agent's log to rotate the log every 6 days or when the size is 128MB. The `init.sls` script is updated to trigger this logrotate policy as well.
The configuration follows the rules for https://github.com/hortonworks/cloudbreak/blob/master/freeipa/src/main/resources/freeipa-salt/salt/logrotate/conf/ipabackup.

CDPAM-1403 | Add logrotate conf to enable log rotation for ccmv2 agent logs

---

Makefile

Image name length change affects GCP and Azure. Both are verified:
http://ci-cloudbreak.eng.hortonworks.com/view/e2e-test/job/api-e2e-imagevalidator-azure/1123/
http://ci-cloudbreak.eng.hortonworks.com/view/e2e-test/job/api-e2e-imagevalidator-gcp/178/

CB-11774 Include stack patch version and seconds into the image name

---

.gitignore
Makefile
docker/yarn-loadbalancer/Dockerfile
docker/yarn-loadbalancer/configuration-files/haproxy.cfg
docker/yarn-loadbalancer/image-runtime-scripts/start-services-script.sh

Jira: https://jira.cloudera.com/browse/CB-10092
This serves to add a new image to be used for YCloud datalake loadbalancers. I am curious as to how the image is put into the official Cloudera catalog, do I have to do anything for that or will it be done automatically?
Specifically, this will simply run the haproxy service, pointing at the gateway servers. I based this off the centos7 image and removed all of the extraneous Salt stuff. Please let me know if I can remove anything else to make this light.
This has been tested with a light duty  and a medium duty YCloud datalake and has worked. 
The test catalog that is in this branch will be deleted before I merge anything, I am just pointing my local cloudbreak at it for testing at the moment.
Thanks!

CB-10092: Adding an image for haproxy for YCloud loadbalancer support.

---

saltstack/base/salt/ccmv2-inverting-proxy-agent/init.sls

Downgrade go version to 1.14.8 to suppress the issue with using wildcards in CN field of inverting proxy server cert

CDPAM-1544 | Update the inverting proxy agent version with the fix for CDPAM-1544

---

saltstack/base/salt/ccmv2-inverting-proxy-agent/init.sls

Bumps version of inverting-proxy to 81.
Adds v1 of the tunneling protocol which cuts down the number of http calls from 3 to 2.
See [CDPAM-1488](https://jira.cloudera.com/browse/CDPAM-1488)

CDPAM-1488: Communication with Kubernetes is Slow

---

saltstack/base/salt/prerequisites/pip.sls

filecollector: pid, fluent-logger
metrics collector: cm_client
(both filecollector and metrics collector is part of cdp-telemetry binary, which has these dependencies compiled to c code)

Remove unused pip deps.

---

saltstack/base/salt/ccmv2-inverting-proxy-agent/init.sls

Reverts hortonworks/cloudbreak-images#554
The latest build of agent has introduced a regression causing env failures. The old agent works as expected.
Please refer https://jira.cloudera.com/browse/CDPAM-1613

Revert "CDPAM-1488: Communication with Kubernetes is Slow"

---

Makefile
saltstack/base/salt/telemetry/init.sls

see https://github.com/hortonworks/cloudbreak-images/pull/551 regarding the changes (cdp-telemetry - cdp-doctor support for the commands)

CDPAM-1531. Update cdp-telemetry version (role: v8 , version: 0.4.3)

---

saltstack/freeipa/salt/freeipa/init.sls

Remove node exporter check from the health agent as we are going to remove this from the images. The thunderhead jenkins build is " Agent Cloudera FreeIPA Health freeipa-health-agent = 0.1-20210511182923git9197412 freeipa-health-agent(x86-64) = 0.1-20210511182923git9197412"

CB-12420: Remove node exporter from FreeIPA health agent checks

---

saltstack/freeipa/salt/freeipa/init.sls

Reverts hortonworks/cloudbreak-images#564
as the version is wrong. 
The correct one is this one. And I've verified it by install the rpm
freeipa-health-agent-0.1-20210517150203gitab017e0.x86_64.rpm

Revert "CB-12420: Remove node exporter from FreeIPA health agent checks"

---

saltstack/final/salt/cis-controls/init.sls

See the ticket for more details. It should be re-added as soon as it is ensured that it no longer blocks image burning.

CB-12848: Temporarily removed the aide package

---

saltstack/base/salt/ccmv2/init.sls

Bumps version of agent to 1.0.0-b117. This allows connections to remote un-trusted endpoints.
This is required for experiences to connect to vendor managed Kubernetes clusters.

CDPAM-1771: Cluster Proxy fails with Kubernetes due to an internal error

---

saltstack/base/salt/prerequisites/usr/bin/user-data-helper.sh

as there is no /etc/cdp directory present and echoing items fail
restricting proxy.env file to U and G only (revoking A)

CB-12989 proxy.env file is not created

---

saltstack/base/salt/ccmv2/init.sls

The test builds haven't been triggered yet due to https://jira.cloudera.com/browse/RELENG-14321 . In the meantime, please review this.
The build number is **1.0.0-b137**

CDPAM-1816 | access logs dont get created for jumpgate agent

---

saltstack/base/salt/prerequisites/packages.sls

From AWS documentation: "Although the awscli package is available in repositories for other package managers such as apt and yum, these are not produced, managed, or supported by AWS. We recommend that you install the AWS CLI from only the official AWS distribution points"

CDPR-33 Install awscli from archive instead of package manager

---

saltstack/base/salt/fluent/init.sls
saltstack/base/salt/telemetry/init.sls
scripts/packer.sh

Telemetry and logging agent can be configured by own urls. If the parameters are stayed empty then the latest versions will be installed.

CDPR-16: Resolve to make the telemetry and logging agent packages configurable

---

packer.json
saltstack/final/salt/cleanup/tmp/generate-package-versions.sh
scripts/pp_json.sh

The package versions block of freeIPA related images should also be extended with the cloudbreak images repository revision number similarly to the cb images therefore the necessary code snippet was moved to a common part which is executed in both cases .

CB-13841: Add the cloudbreak images repository revision number to the package version of freeipa image

---

Makefile

Currently on the master branch the Makefile provides an explicit value for the Jumpgate RPM URL, however on rhel_support this used to be something that comes from the caller - e.g. the wrapper script or from the Jenkins job. Now that master is merged to rhel_support to keep branch differences at a minimum, we ended up with a situation, where the explicit value always overwrites the parameterized one.

CDPR-50: Makefile overwrites Jumpgate RPM URL

---

Makefile

The jumpgate agent url now is checked, if it is not specified then the its defined default url value will be introduced.

CB-14160: Makefile overwrites Jumpgate RPM URL

---

Makefile
saltstack/final/salt/cleanup/tmp/generate-package-versions.sh

If the package version generation is not possible due to the used regex is not match we should interrupt the flow.

CDPR-51: Interrupt the flow if parsing of package versions by regex not possible

---

saltstack/base/salt/prerequisites/dnsmasq.sls

Dnsmasq needs to be stopped and disabled otherwise unbound service will not start.

CDPR-52: Prevent dnsmasq from starting on RHEL VMs

---

saltstack/base/salt/ccmv2/init.sls
saltstack/final/salt/cis-controls/init.sls

Root user login via SSH needs to be disabled from runtime version 7.2.8

CB-9069: Root user login via SSH needs to be disabled

---

scripts/generate-delta-package-list.sh

Fixed the function that is used for calculating difference between base and completed rpm lists.

CB-15729: Weird differences between AWS and Azure versions of the same Runtime image

---

docker/yarn-loadbalancer/configuration-files/haproxy.cfg
docker/yarn-loadbalancer/image-runtime-scripts/start-services-script.sh

1. For Oozie HA to work YCloud needs to listen on multiple ports.
2. For Knox HA failover testing to work the check port of the HAproxy should be Knox port 8443

CB-14420 CB-14833 Enable Oozie HA and Knox HA failover testing in YCloud

---

Makefile

Since that cloudbreak-images-metadata repo is not available to everyone, the manifest files should be copied to s3 bucket similarly to catalogs.

CB-15988: Copy image manifest to s3 bucket

---

Makefile

There was a file name error which affects the uploading of manifest files, the proper file name should be extended with the build id.

CB-16037: Extend the proper manifest file name with build id in upload

---

saltstack/freeipa/salt/freeipa/init.sls
saltstack/freeipa/salt/freeipa/tmp/stageuser.py.patch
saltstack/freeipa/salt/freeipa/tmp/user.py.patch

This commit patches user and stageuser commands to skip some
behaviors that take a long time but are not needed for our
use case.
stageuser_activate has been modified to:
- not add user to default group (ipausers)
- not run a query to populate the return value
user_disable and user_del have been modified to:
- not check whether the user being disabled/deleted is the
last enabled member of a protected group (i.e., admins).
This check was performed regardless of whether the user
is a member of the admins group or not. Usersync has
protections to not modify the admin user, so this check
is extraneous. A flag was added to this check so that the
default behavior is maintained for callers outside of
usersync.
user_add has been modified to:
- not add user to the default group (ipausers)

CB-15450. Patch stageuser and user commands for better performance

---

packer.json
saltstack/base/salt/prerequisites/user.sls
saltstack/final/salt/cleanup/init.sls
saltstack/final/salt/cleanup/kernel.sls
saltstack/final/salt/cleanup/user.sls
scripts/reboot.sh
scripts/salt-final.sh
scripts/salt-setup.sh

To be able to remove old kernels after system update, the machine has to be rebooted. To achieve this, the final saltstate was extracted to a new salt-final.sh script, and a reboot is issued before running it.

CB-15727 Remove old kernels

---

saltstack/hortonworks/pillar/java/init.sls

We need JDK 11 installed alongside JDK8 on our prewarmed images

CB-16538: Burn prewarmed images with JDK11 installed alongside JDK8

---

saltstack/base/salt/prerequisites/usr/bin/user-data-helper.sh

As it was always used as "http" and always filled the "http_proxy" environment variable

CB-16575 Use proxy protocol

---

saltstack/base/salt/chrony/init.sls
saltstack/base/salt/top.sls

We got news from a customer that chrony crashed on their VMs, even though the customer has failed to produce evidence for this so far.
I checked that after killing chrony it is not restarted, since in the unit file there is no restart on failure  set.

CB-14431: Chrony is not restarted if it crashes

---

scripts/get-salt-version.sh

Since an error was reported for the latest version (3004.1), we switched to version 3002.8

CB-16854: Change the salt version to 3002.8

---

saltstack/base/salt/monitoring/cdp-prometheus.sls
saltstack/base/salt/monitoring/init.sls
saltstack/final/salt/cleanup/tmp/generate-package-versions.sh

Install prometheus that we will use for compute monitoring.
Jenkins builds:
- http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/6028/console
- http://build.eng.hortonworks.com/job/imagecatalog-v3-append/4360/console
I only changed the name of the package in the `/tmp/package-versions.json` from prometheus to cdp-prometheus.

CB-17500 Install prometheus on base image

---

scripts/changelog/collect-package-changelogs.sh

We need a simple script that iterates through all the RPM packages of the OS and using "rpm -q --changelog" it generates a .txt file for each package in a separate folder for later processing. This script will have to be executed on VMs started with our Cloudera Runtime or FreeIPA images by Packer.

CB-18203: Implement a script that generates individual package changelogs

---

saltstack/final/salt/cis-controls/init.sls

Basically this is the highest value allowed by Azure Marketplace,
however CB will change this to 1800 during instance provisioning,
because a much larger value is essential to our own image validation
and E2E processes.
**Also DON'T MERGE this before Cloudbreak 2.62.0-b84 reaches production
or you unleash Ragnarok on us by crippling image releases!**
Warned you...

CB-18227: Changed SSHD ClientAliveInterval to 235

---

Makefile
scripts/changelog/packer.json
scripts/changelog/packer.sh

The easiest way to grab precise change logs is directly from images - since we support different OSes (though right now, we should concentrate on CentOS mainly!) and cloud providers, Packer could be a helpful facade here - it should create a VM in the cloud, execute our generator script and then it should terminate and clean up the VM.

CB-18201: Implement a packer setup to generate RPM change logs from a VM

---

saltstack/base/salt/prerequisites/usr/bin/ccmv2-helper.sh

Take IV as parameter instead of fixed value.
If the HMAC key was provided, then the HMAC digest is
expected, the latter is computed in-place as well
and is compared against the received digest.

CB-16947 Apply AES256 in decrypting key and SHA512 for HMAC check.

---

saltstack/final/salt/cis-controls/init.sls

Apparently the Azure Marketplace publishing process does not accept the highest value (235), which should be accepted btw. according to their documentation.

CB-18227: Lowered ClientAliveInterval even further

---

saltstack/base/salt/prerequisites/jinja.sls
saltstack/base/salt/prerequisites/path.sls
saltstack/base/salt/prerequisites/pip.sls
saltstack/freeipa/salt/ipaconsistency/init.sls
scripts/generate-delta-package-list.sh
scripts/salt-install.sh

This enables us to burn images with the following combination:
- Python 3.6 (without SaltStack relying on Python 2.7 in any way)
- CentOS 7
- SaltStack 3001.8

CB-18927: Ensure SaltStack uses Python 3.6 during image burning

---

Makefile
scripts/changelog/collect-package-changelogs.sh
scripts/changelog/packer.json
scripts/changelog/packer.sh

Now we use packer version 1.4.2 that cannot support the skip create ami feature, so we should increase the version number >= 1.7.0 where this feature was provided at the first time. The latest version will be tried to used.

CB-18202: Increase packer version due to the skip create ami feature

---

saltstack/base/salt/prerequisites/etc/profile.d/timeout.sh
saltstack/base/salt/prerequisites/init.sls
saltstack/base/salt/prerequisites/timeout.sls
saltstack/final/salt/cis-controls/init.sls

Currently the timeout was added only for Centos 7. Refactored the related states:
- it's applied to all OS
- matches the structure of how we configure profile

CB-19582 CB-19583 Configure SSH/user session timeout for all systems

---

Makefile

update metering agent to use latest build, 1.0.0-b8780.
CDPCP-8354

CDPCP-8354: Upgrade base images for thunderhead-metering-heartbeat-application

---

saltstack/base/salt/prerequisites/ssh.sls
saltstack/final/salt/cis-controls/init.sls

In case of gov cloud image replace the current text after login.
- moved the config from cis to the common configuration so it's added for every OS
- `-` aroung `%` is to ensure no blank lines are inserted
- `indent(8)` to ensure the rendered state file is valid, without formatting the text itself

CB-19581 Gov cloud compatible SSH banner

---

Makefile
packer.json
saltstack/base/salt/postgresql/init.sls
saltstack/base/salt/postgresql/scripts/conf_pgconfig_path.sh
saltstack/base/salt/python3/init.sls
saltstack/base/salt/top.sls
saltstack/freeipa/salt/ipaconsistency/init.sls
saltstack/hortonworks/salt/java/init.sls
saltstack/hortonworks/salt/pre-warm/tmp/pre_warm_parcels.py
scripts/generate-delta-package-list.sh
scripts/get-salt-version.sh
scripts/rhel8_salt_fix.patch
scripts/salt-install.sh
scripts/salt-setup.sh
scripts/sparseimage/packer.json

Supersedes https://github.com/hortonworks/cloudbreak-images/pull/740
- Made sure we install the right Python version for the right OS (CB-18380)
- Increased AMI base snapshot size (CB-19722)
- Fixed rh-python38 root path (CB-19812)
- Fixed psycopg2 installation (CB-19812)
- Removed a leftover python2 reference (CB-19529)
- Python3-ified pre_warm_parcels.py (CB-19529)
- Added code to update Python 3.6 to Python 3.8 (CB-19529)
- Set Python 3.8 as "python" globally for RHEL 8 as CM currently needs this to work! (CB-20079)
- Updated path with pg_config for PsycoPG installed by CB (CB-20079)
- Added postgresql11-devel
- Increased SaltStack version to 3001.8 across the board for everything including and above 7.2.6
- Made sure that FreeIPA will be installed with Python 3.6 and 2.7 on RHEL and …

CB-18380: Bumped Python version to 3.8, made some cleanup

---

Makefile
scripts/bundle-gcp-image.sh

Skip creating compute images on GCP as we are only using their tar.gz counterpart.

CB-19862 Do not create compute images on GCP for 7.2.17 runtime

---

saltstack/hortonworks/salt/java/init.sls
scripts/salt-install.sh

The append of JAVA_HOME variable to systemd's default environment variables should result in a line without being a comment even it was a commented out line before. Also fix the runtime check for python version condition.

CB-20929 Fix missing JAVA_HOME env variable and python version condition

---

saltstack/base/salt/postgresql/init.sls
saltstack/base/salt/python3/init.sls
scripts/salt-install.sh
scripts/salt-setup.sh

This should also solve **CB-21011** and **CB-21199**.
**Original requirement from Slack:**
7.2.16.2 (and all subsequent 7.2.16.x service packs) CentOS7 images:
Python 2 present on the Cloudbreak images
Python 3 present on the Cloudbreak images, Py 3.6 remains the default for “python3”, but Py3.8 is also present (for Hue)
7.2.17 (and all subsequent 7.2.17 service packs:) CentOS7 images:
Python 2 present on the Cloudbreak images
Python 3 present on the Cloudbreak images, Py 3.6 remains the default for “python3", but Py3.8 is also present (for Hue)
7.2.17 (and all subsequent 7.2.17 service packs:) RHEL8 images:
Python 2 present on the Cloudbreak images
Python 3 present on the Cloudbreak images, Py 3.8 becomes the default for “python3”, but Py3.6 is also present (for legacy apps, including …

CB-20961: Multiple Python3 versions on the same image, depending on image type and RT version

---

saltstack/base/salt/prerequisites/usr/bin/ccmv2-helper.sh

This PR makes the required changes to make Jumpgate-agent certificate and key parameters optional as we would not be generating those in CCMv2 service when FIPS is enabled. Changes are tested with below scenarios:
Testing:
- Create an environment with only a new freeipa image (which is burned with changes from this CDPAM-3883 branch) and no CCMv2 side changes (without one-way TLS)
- Create an environment with only a new freeipa image and no CCMv2 side changes (with one-way TLS)
- Create an environment with a new freeipa image and new CCMv2 docker image (without one-way TLS and fips enabled)
- Create an environment with a new freeipa image and new CCMv2 docker image (with one-way TLS and fips enabled)
- Create an environment with a new freeipa image and new CCMv2 docker image (without …

CDPAM-3882 | Make jumpgate agent certificate and key parameters options for CCMv2

---

Makefile

This PR updates the Jumpgate agent version from 3.0.3 to 3.0.4 for our new release.
Changes are tested with CCM test runs and CCM e2e test runs with custom images. Below are the image IDs:
```
AWS: be143b3e-a16e-43c3-9064-be0b610b26dd
AWS_GOV: 5665fcb5-93bd-4d6e-a43c-b8a708ae11fd
Azure: 4208cf32-9584-491a-a8df-f3255c945526
GCP: 3438bced-6df7-4c88-8a14-2833ecd75d69
```

CDPAM-3971 | Update jumpgate agent version to support CDPAM-1835

---

saltstack/base/salt/ccmv2/cdp/bin/ccmv2/generate-config.sh

To the config.toml for Jumpgate agent.
The environment variable used `CDP_API_ENDPOINT_URL` originates from the user data script.

CB-21371 Add the cdpEndpoint parameter

---

Makefile
packer.json
saltstack/base/salt/prerequisites/authconfig.sls
saltstack/base/salt/prerequisites/disable_ipv6.sls
saltstack/base/salt/prerequisites/user_uid.sls
scripts/salt-install.sh

* Update Azure and GCP base images
* Force select sssd auth profile
* Create missing ifcfg files
* Update cloudera scm user and group ids to avoid conflict
* Update python36 in case of python3 fails
* Install pyasn1-modules for IdM

CB-21747 Adds support to burn RHEL8 FreeIPA images for commercial clouds

---

Makefile

This PR updates the Jumpgate agent version to 3.0.6 for our new release.
Changes are tested with CCM test runs and CCM e2e test runs with custom images. Below are the image IDs:
`1.  AWS- 30325c00-383c-43ab-8dd3-cc9d6df57462
2. AWS-Gov- d9dc9a37-5992-406a-aba3-381ff88fcdc2
3. Azure : 1940c460-d8b9-4d49-b912-fa8b50748ecb
4. GCP: bf335aaa-5aed-44f3-8a96-fbb28788c83d `

CDPAM-4086|Update jumpgate agent version to v3.0.6

---

Makefile

This PR sets back to jumpgate-agent version to 3.0.3, this is required till with test one-tls related fix for jumpgate agent version 3.0.6. Once that change is tested and react for prod, this will be updated back to jumpgate agent version 3.0.6.

Update jumpgate agent version back to 3.0.3

---

Makefile

The ITs and E2E tests have been run for the following images:
```
AWS: 9dd48cd5-cfd5-41aa-9a10-cde69067d1aa
Azure: c8140b5b-7378-4bfe-9f87-8143cbe3ca3c
GCP: 20fef85e-e0ae-4d1f-aec8-7703422fa272
```
The test URLs:
ITs: 
1. https://quanta.infra.cloudera.com/#/runDetails?gtn=42054045
2. https://quanta.infra.cloudera.com/#/testSetHistory?endTime=1686572217000&startTime=1685017017000&includeUnofficialRuns=true&tags=cli_token%3Dfl8352ugl5
E2E tests:
1. https://quanta.infra.cloudera.com/#/testSetHistory?endTime=1686579223000&startTime=1685024023000&includeUnofficialRuns=true&tags=cli_token%3D7b0kp5q8f2
2. https://quanta.infra.cloudera.com/#/runDetails?gtn=42050761

jumpgate-3.0.7 | Fix the RC in CDPAM-4153 and update the jumpgate agent version

---

scripts/packer.sh

For CentOS 7 the new version is optional, so disabled it. For RHEL 8 w/ FIPS, it's mandatory, so it's still a blocker bug and a new RPM will be needed.

CB-22127: Temporary fix for the broken cdp-logging-agent

---

saltstack/base/salt/telemetry/centos/init.sls
scripts/packer.sh

For CentOS 7 the new version is optional, so disabled it. For RHEL 8 w/ FIPS, it's mandatory, so it's still a blocker bug and a new RPM will be needed. Had to re-write this due to the weird RPM selection logic...

CB-22127: Temporary fix for the broken cdp-logging-agent (v2)

---

scripts/packer.sh

Added these hardcoded URLs till we figure out how to differentiate between OSes and versions properly and clean up all the mess!

CB-22215: Fixed cdp-logging-agent and cdp-telemetry URLs for CentOS 7

---

saltstack/base/salt/prerequisites/selinux.sls

Validated images:
1. http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-azure/2538/
2. http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-azure/2537/
SELinux status:
```
[root@azure-test-d88c2b91-idbroker0 cloudbreak]# sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   permissive
Mode from config file:          permissive
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      31
[root@azure-test-d88c2b91-idbroker0 cloudbreak]# grep "SELinux is preventing" /var/log/messages
[root@azure-test-d88c2b91-idbroker0 cloudbreak]# 
```

CB-22117 CIS: Enable SELinux permissive mode

---

saltstack/final/salt/cleanup/tmp/generate-package-versions.sh

Image burn with these changes: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/1405/
Image catalog entry:
```
{
"created": 1687349567,
"published": 1687351907,
"date": "2023-06-21",
"description": "Official Cloudbreak image",
"images": {
"azure": {
"West US": "https://cldrwestus.blob.core.windows.net/images/cb-cdh--1687349559.vhd"
}
},
"os": "centos7",
"os_type": "redhat7",
"uuid": "ffcd862b-b973-4052-8dc9-3015f0da1582",
"package-versions": {
"blackbox-exporter": "0.19.0",
"cdp-logging-agent": "0.3.6",
"cdp-minifi-agent": "1.22.07",
"cdp-prometheus": "2.36.2",
"cdp-request-signer": "0.2.4",
"cdp-telemetry": "0.4.31",
"cloudbreak_images": "2604e8d1835fcc34b4bd05206242034c8858652f",
"inverting-proxy-agent": "3.0.7-b1",
"inverting-proxy-agent_gbn": …
```

CB-22295 Generate java package versions for base images

---

docker/centos7.9/Dockerfile
saltstack/base/pillar/prerequisites/init.sls
saltstack/base/salt/postgresql/init.sls
saltstack/base/salt/postgresql/scripts/conf_pgsql_listen_address.sh
saltstack/base/salt/prerequisites/corkscrew.sls
saltstack/base/salt/top.sls
saltstack/final/salt/cis-controls/init.sls

Additional fixes to make ycloud image burning work:
- Disable CIS for ycloud (sysctl commands were failing and we do not need CIS internally)
- Revert corkscrew building on ycloud, because cloning its repo is disabled on dev machines
- Change subtype detection from virtualization to yarn-private directory check
- Unify subtype checks

CB-22263 Bump ycloud base image version

---

scripts/packer.sh

Enabled new version of the metering agent RPM for the commercial cloud

CB-22455: Enabled new version of the metering agent RPM

---

Makefile
scripts/check-image-regions.sh

Only prod catalog needs all regions of an image. Before that we should only store the images in a few regions where testing takes place.
We should copy the images only to us-west-2 and eu-central after validation, like it is now. The rest of the copy should happen right before prod promotion. If a complaint arrives that someone needs images in other regions as well for testing/development/etc. and the request is justified (e.g. other regions are slow or something) we'll re-enable early copy for those regions as well.

CB-12687: Copy image to all regions as part of prod promotion

---

Makefile
scripts/check-image-regions.sh

The azure related regions input parameter contains spaces this caused issue in script execution.

CB-22611: Fix the input of region checker script

---

Makefile

we add support for the Central US region.

CB-22661: Provisioning Azure env on mow-int fails - add Central US region to first copy phase

---

saltstack/hortonworks/salt/java/init.sls

Test build: /job/cloudbreak-multi-packer-image-builder-salt-v3/1776/console

CB-22679: Removed OpenJDK 17 from CentOS 7 images

---

saltstack/final/salt/cis-controls/scripts/cis_control.sh

The workaround can be removed when CM side fix is done by OPSAPS-68448

CB-23006 Temporarily disable tmp noexec as CM fails to start REGIONSERVER

---

saltstack/final/salt/cis-controls/common.sls

http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/2216
```
[root@ip-10-112-2-38 cloudbreak]# cat /etc/pam.d/su
#%PAM-1.0
auth		required	pam_env.so
auth		sufficient	pam_rootok.so
#auth		sufficient	pam_wheel.so trust use_uid
auth required pam_wheel.so use_uid group=sugroup
auth		substack	system-auth
auth		include		postlogin
account		sufficient	pam_succeed_if.so uid = 0 use_uid quiet
account		include		system-auth
password	include		system-auth
session		include		system-auth
session		include		postlogin
session		optional	pam_xauth.so
```
http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/2217
```
[root@ip-10-112-0-33 cloudbreak]# cat /etc/pam.d/su
#%PAM-1.0
auth		sufficient	pam_rootok.so
#auth		sufficient	pam_wheel.so trust use_uid …
```

CB-23120 Fix /etc/pam.d/su sugroup

---

saltstack/hortonworks/salt/java/init.sls

Test burn successful - removed this temporarily, because the proper and supported way to install JDK 21 is still being clarified with RedHat support.

CB23402: Temporarily removed JDK21

---

scripts/packer.sh

Test builds:
CentOS 7: /cloudbreak-multi-packer-image-builder-salt-v3/2528/
RHEL 8: /job/cloudbreak-multi-packer-image-builder-salt-v3/2529/

CB-23468: Added new version of telemetry and logging agent RPMs

---

Makefile

Azure SDK contains the correct entry, matching the Azure CLI now, so it could be re-renamed to its original form.
public static final Region ASIA_SOUTHEAST = new Region("southeastasia", "Southeast Asia");

BUG-95449 - Image not found for Azure in region Southeast Asia

---

saltstack/base/salt/ccm-client/cdp/bin/reverse-tunnel.sh

Burning a test image is pointless - the script gets activated during provisioning. Instead, I tested the replacement code using the "black box" methodology - e.g. both code parts, the old and the new should yield the same output in case of the same input. Here are the results:
The only observation is that if the input is shorter than 16 chars, the string "0a" is also appended in case of the new implementation. Given past examples and the fact that the implementation cuts down the string from whatever value it has to 16 chars, this should not cause a problem.

CB-23922: Replaced xxd with od so CCMv1 based envs won't be broken

---

saltstack/base/salt/postgresql/init.sls

The perl-IPC-Run package is not available at this time in any of the repositories on GOV which is required for postgresql14-devel
AWS: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/3024
AWS_GOV: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/3020

CB-20937 Only set flags for postgres install on AWS_GOV

---

saltstack/base/salt/postgresql/init.sls
scripts/salt-install.sh

Test image build: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/3118/

CB-23748: Added Python 3.11 to base and runtime images

---

scripts/salt-install.sh

On Azure and GCP it is not installed automatically with python3.11 so we have to add it to yum install
AWS: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/3150/ 
Azure: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/3149/
GCP: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/3151/

CB-23748 Make sure python3.11-pip is installed

---

saltstack/base/salt/prerequisites/packages.sls

Successful validation: http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-awsgov/362/

CB-23918: Lock in RHEL 8.8 as 8.9 can caused problems for JDK 8

---

saltstack/base/salt/postgresql/init.sls
saltstack/base/salt/postgresql/scripts/conf_pgconfig_path.sh

Centos7 http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-aws/3261/ 
install 10,11,14
default 10
RHEL8 AWS/GCP/Azure http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-aws/3263/
install 11,14
default 14
RHEL8 YARN
install 14
default 14
/etc/environment was empty on all providers I have tried so I tried a test run where I first set the file:
http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/3267
```
aws-centos7:           ID: set-etc-environment-path-pgsql10-bin
aws-centos7:     Function: file.replace
aws-centos7:         Name: /etc/environment
aws-centos7:       Result: True
aws-centos7:      Comment: Changes were made
aws-centos7:      Started: 11:05:22.429850
aws-centos7:     Duration: 5.158 ms
aws-centos7: …
```

CB-24059 Update default Postgres versions

---

Makefile
saltstack/base/salt/salt/etc/salt/master.d/custom.conf
scripts/get-salt-version.sh

AWS 7.2.18: http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-aws/3241/
Azure 7.2.18: http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-azure/2973/
GCP 7.2.18: http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-gcp/1788/
AWS base: http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-aws/3245/
AWS 7.2.16: http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-aws/3250/

Burn image with Salt version 3006.4

---

saltstack/final/salt/krb5/init.sls

Test build: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/3583/

CB-24609: Disabled redundant SSSD config dir inclusion

---

Makefile

Test build: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/3712/

CB-24907: Extended disk size for Runtime 7.3.0+

---

saltstack/base/salt/prerequisites/usr/bin/ccmv2-connectivity-check.sh

The `curl` command cannot communicate with the target host otherwise.

CB-25091 Source proxy.env on CCMv2 upgrade connectivity check

---

saltstack/base/salt/prerequisites/packages.sls

https://access.redhat.com/solutions/3592
test image burn: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/3826/console
```Installed Packages
Name         : sos
Version      : 4.6.0
Release      : 5.el8
Architecture : noarch
Size         : 2.9 M
Source       : sos-4.6.0-5.el8.src.rpm
Repository   : @System
From repo    : ubi-8.8-baseos-cldr
Summary      : A set of tools to gather troubleshooting information from a system
URL          : https://github.com/sosreport/sos
License      : GPL-2.0-or-later
Description  : Sos is a set of tools that gathers information about system
: hardware and configuration. The information can then be used for
: diagnostic purposes and debugging. Sos is commonly used to help
: support technicians and developers.
```
From the …

CB-25087 Add sosreport to image

---

saltstack/base/salt/postgresql/init.sls

```
[cloudbreak@ip-10-83-196-130 ~]$ systemctl status postgresql-14
● postgresql-14.service - PostgreSQL 14 database server
Loaded: loaded (/usr/lib/systemd/system/postgresql-14.service; disabled; vendor preset: disabled)
Active: inactive (dead)
Docs: https://www.postgresql.org/docs/14/static/
```

CB-25364 Disable postgres

---

saltstack/base/salt/postgresql/init.sls

On centos7 the default postgresql service is needed for CB, but this alias is not resolved when the service is disabled
```
[root@ip-10-84-214-151 cloudbreak]# systemctl list-unit-files |grep postg
postgresql-10.service                         disabled
postgresql-11.service                         disabled
postgresql-14.service                         disabled
[root@ip-10-84-214-151 cloudbreak]# systemctl enable postgresql-10
Created symlink from /etc/systemd/system/postgresql.service to /usr/lib/systemd/system/postgresql-10.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/postgresql-10.service to /usr/lib/systemd/system/postgresql-10.service.
[root@ip-10-84-214-151 cloudbreak]# systemctl list-unit-files |grep postg
postgresql-10.service …
```

CB-25364 Only disable postgresql for rhel8

---

saltstack/base/salt/prerequisites/packages.sls

Test builds:
- http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/4164/ (AWS, should not be affected at all)
- http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/4165/ (GCP, package should be removed without problems)

CB-25246: Disabled automatic DNF updates

---

saltstack/base/salt/prerequisites/user_uid.sls

On Azure RHEL8 the cloudera-scm uid and gid collides with sssd, so as a fix this was modified to 10001, but that caused permission issues when upgrading from centos7 to rhel8. The actual fix is to change the sssd uid and gid to free them up for cloudera-scm.
RHEL8 7.2.17 runs:
http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-v2/171/
http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-v2/164/
http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-v2/174/

CB-24956 Fix cloudera-scm uid/gid on RHEL8

---

Makefile
packer.json
saltstack/base/salt/mount/init.sls
saltstack/final/salt/cis-controls/scripts/cis_control.sh
saltstack/final/salt/cleanup/init.sls
saltstack/final/salt/cleanup/mount.sls
saltstack/hortonworks/salt/pre-warm/tmp/install_cdh.sh
saltstack/hortonworks/salt/pre-warm/tmp/pre_warm_parcels.py
scripts/get-image-size.sh
scripts/get-salt-version.sh
scripts/packer-command.sh
scripts/packer.sh
scripts/salt-final.sh
scripts/salt-setup.sh
scripts/utils.sh

Temp files moved:
- Parcels (empty files were left in place to make CM happy)
- Ansible stuff needed for cis hardening
Storage requirements changed for RHEL8:
- Azure needs to 64GB, used to require 90GB for 7.2.18 (LVMs of the source image can not be shrinked so this is the minimum)
- CDH version 7.2.18+ needs 52GB, used to require 72GB
- Older runtimes need 48GB, used to require 64GB
Other improvements:
- Upgrade to latest Packer
- Move image size calculation to separate script
- Show storage usage at the end of image burning
- Remove --retcode-passthrough from salt highstates to fail on error
Test images
- Centos7 7.2.17
- http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/4004/
- http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-s …

CB-23061 Move temp files to attached disk to save space

---

saltstack/base/salt/luks/bin/create-luks-volume.sh
saltstack/base/salt/luks/bin/reopen-luks-volume.sh
saltstack/base/salt/luks/etc/systemd/system/cdp-reopen-luks-volume.service
saltstack/base/salt/luks/init.sls
saltstack/base/salt/prerequisites/packages.sls
saltstack/base/salt/prerequisites/usr/bin/user-data-helper.sh
saltstack/base/salt/top.sls
saltstack/freeipa/salt/ipaconsistency/init.sls
scripts/salt-install.sh

On first boot (started by user-data-helper.sh):
1. Generate passphrase
2. Encrypt passphrase and store ciphertext
3. Create backing file
4. Create loop device on the backing file
5. Create LUKS volume on the loop device
6. Open LUKS volume
7. Create file system inside the LUKS volume
8. Mount LUKS volume
On subsequent boots (done by reopen-luks-volume.service):
1. Recreate loop device on the backing file
2. Decrypt passphrase ciphertext
3. Reopen LUKS volume
4. Remount LUKS volume
Dependencies added:
- cryptsetup
- aws-encryption-sdk-cli
- Python 3.8 to RHEL8 freeipa images (needed for aws-encryption-sdk-cli)

CB-24163, CB-24164, CB-24165, CB-24166, CB-24175: LUKS volume creation

---

Makefile
docker/redhat8/Dockerfile

**AWS based image tested using** 
CentOS
```
{
"created": 1713976483,
"published": 1713980461,
"date": "2024-04-24",
"description": "Official Cloudbreak image",
"images": {
"aws": {
"us-west-1": "ami-07bfde7b8e8b6507a"
}
},
"os": "centos7",
"os_type": "redhat7",
"uuid": "0eadafc6-315d-4599-80ed-6130f1dd15b1",
"package-versions": {
"blackbox-exporter": "0.19.0",
"cdp-logging-agent": "1.3.2_b1",
"cdp-minifi-agent": "1.22.07",
"cdp-prometheus": "2.36.2",
"cdp-request-signer": "0.2.4",
"cdp-telemetry": "1.3.2_b1",
"cloudbreak_images": "9eb34da0142d90da75f9cd949010b850f4861fe2",
"freeipa-health-agent": "0.1-20240306130845git17cc467",
"freeipa-ldap-agent": "1.0.0-b12478",
"freeipa-plugin": "1.0-20240306130845git17cc467.el7",
"imds": "v2",
"inverting-proxy-agent": "3.4.0-b48", …
```

Bump-up new version of jumpgate agent to 3.0.8

---

saltstack/base/salt/nginx/etc/nginx/ssl.conf

RHEL8 7.2.18 Test build: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/4609/ 
(Successful validation: http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-v2/618/)
RHEL8 FreeIPA Test build: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/4628/
(Successful validation: http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-v2/633/)
CentOS7 FreeIPA Test build: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/4616/
CentOS7 7.2.16 Test build: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/4617/
**UPDATE**: Dropped support for this on CentOS 7 as it consistently breaks FreeIPA on CentOS 7, however given it's nearly EOL, …

CB-26169: Disabled weak SSL ciphers

---

Makefile

Test build: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/4724/ - ✅ 
Validation: http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-v2/694/ - ⏳

CB-26331: Added missing arch info for AWS Gov builds

---

saltstack/freeipa/salt/ipaconsistency/init.sls
scripts/salt-install.sh

Test build: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/4726/ - ✅ 
Validation:  - FAILS, but not because of this issue. Currently it fails even for images which are re-burns of images already in prod.

CB-26321: Fixed 'CIPA' patch checks

---

saltstack/base/salt/userdata-secrets/bin/cdp-retrieve-userdata-secrets.sh

Previously, when an instance would try to retrieve its userdata secret and the secret's resource policy hasn't been updated yet, the script would exit because the AWS CLI would return an `AccessDeniedException` and exit with an exit code of `254`. Modified the script, so that it wouldn't exit immediately when the AWS CLI call to retrieve the secret returns an `AccessDeniedException`. Instead, the script treats `AccessDeniedException`s (and any other exception that would cause the cli to exit with an exit code of `254`) as errors that need to be retried for.

CB-24126: Include `AccessDenied` in the errors we retry for while retrieving userdata secrets

---

Makefile
packer.json
saltstack/final/salt/krb5/init.sls
saltstack/final/salt/metadata/tmp/generate-package-versions.sh
saltstack/final/salt/validate/init.sls
saltstack/hortonworks/salt/java/init.sls
scripts/packer.sh

This commit:
- introduces DEFAULT_JAVA_MAJOR_VERSION at the top level in packer.json
- changes scripts to respect it's value when setting java version and metadata
- adds valdation (~both~ in validation state ~and in the generate package versions script~) to check java version is the same in the var and on the system
- introduces the "hack" for java 8 enctype order only if the default java major version is 8 _and_ the OS is RHEL 8.10
Testing:
image burning rhel 8.10 cdh 7.2.18, verified /etc/krb5.conf.d/crypto-policies contents:
http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/5457/consoleFull
image burning rhel 8.8 cdh 7.3.1, verified /etc/krb5.conf.d/crypto-policies contents:
http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt …

CB-27029 Update handling of major java version

---

packer.json
saltstack/final/salt/krb5/init.sls
saltstack/final/salt/metadata/tmp/generate-package-versions.sh
saltstack/final/salt/validate/init.sls
saltstack/hortonworks/salt/java/init.sls
scripts/packer.sh

previous version of this PR had to be reverted
This commit
- introduces DEFAULT_JAVA_MAJOR_VERSION at the top level in packer.json
- changes scripts to respect it's value when setting java version and metadata
- adds valdation (both in validation state and in the generate package versions script) to check java version is the same in the var and on the system
- fixes an issue with set_openjdk_version_17where it added java version setting in the /etc/profile.d hence executing it at every interactive login

CB-27029 Update handling of major java version #2

---

saltstack/base/salt/luks/bin/reopen-luks-volume.sh
saltstack/base/salt/luks/init.sls

On FreeIPA nodes, DNS resolution is done by the `named-pkcs11` service. This service is not up by the time we are trying to decrypt the passphrase, to remount the LUKS volume by calling AWS KMS, because the files it needs are actually on the encrypted LUKS volume. This creates a chicken and egg problem.
The workaround solution is to use a different DNS server for resolving the KMS endpoint needed for the decryption process:
1. We try the AmazonProvidedDNS server first. If that isn't able to resolve the endpoint to an address, then we try the IP addresses of the DNS servers associated with the VPC the instance is in.
2. After we resolved the endpoint to an address, we add a temporary entry to the `/etc/hosts` file containing the resolved IP and the endpoint. At this point we can decrypt …

CB-26510: Workaround for DNS resolution of KMS endpoint for secret encryption passphrase decryption

---

saltstack/hortonworks/pillar/java/init.sls
saltstack/hortonworks/salt/java/init.sls

http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/5551/
```
"package_versions": {
...
"java": "17",
"java17": "17.0.12",
"java21": "21.0.4",
...
},
```

CB-27275 Remove java 8 and 11 from arm64 images

---

Makefile

CB-26823: Use RHEL 8.10 for FreeIPA images

---

saltstack/hortonworks/pillar/java/init.sls

7.2.18: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/5564/
7.3.1: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/5565/

CB-27290 Remove JDK 11 from x86 based 7.3.1 images

---

Makefile
scripts/bundle-gcp-image.sh
scripts/changelog/packer.json
scripts/changelog/packer.sh

Fix the changelog generation in case of GCP provider, there was a previous improvement where a tar.gz has been stored instead of the concrete image due to cost reduction, so at first we need to create the compute image from tar.gz before changelog generation.

CB-26973: Fix changelog generation in case of redhat8/x86_64

---

saltstack/final/salt/hacks-and-tweaks/init.sls
saltstack/final/salt/hue-hack/init.sls
saltstack/final/salt/top.sls

Test build: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/5729/ - ✅ 
Validation: http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-v2/1643/ - ⏳

CB-27565: Got rid of RHEL 8.10's GCP dns override

---

Makefile
scripts/get-image-size.sh

Test build: https://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/5817/
Validation: not needed, the lack of free space blocked image burning and now with this branch it's now unblocked.

CB-27690: Increased image size for x86-64 images

---

saltstack/final/salt/metadata/tmp/generate-package-versions.sh

```
"uuid": "80a5dbe8-fc44-4b90-b696-da22c47f0af4",
"package-versions": {
"blackbox-exporter": "0.19.0",
"cdp-logging-agent": "1.3.5_b1",
"cdp-prometheus": "2.36.2",
"cdp-request-signer": "1.3.5_b1",
"cdp-telemetry": "1.3.5_b1",
"cloudbreak_images": "79b665f130ee66dfe82ac80a83d2ea96ba2eea4f",
"freeipa-health-agent": "0.1-20240306130845git17cc467",
"freeipa-ldap-agent": "1.0.0-b12478",
"freeipa-plugin": "1.1-b847.el8",
"imds": "v2",
"inverting-proxy-agent": "3.8.0-b23",
"inverting-proxy-agent_gbn": "59355298",
"ipa-server": "4.9.13",
"node-exporter": "1.3.1",
"os-version": "8.10",
"python311": "3.11.9-7.el8_10",
"python36": "3.6.8-39.module+el8.10.0+20784+edafcd43",
"python38": "3.8.17-2.module+el8.9.0+19642+a12b4af6",
"python39": "3.9.19-7.module+el8.10.0+22237+51382d7a",
"salt": …
```

CB-26379 Add ipa-server version to freeipa images' package-versions

---

Makefile

Image burning tests:
- http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/5972/
- http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/5978/
- http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/5979/
Validations:
- http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-v2/1855/
- http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-v2/1859/
- http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-v2/1863/

CB-27728: Burn 7.2.18 images with RHEL 8.10

---

saltstack/final/salt/cis-controls/common.sls
saltstack/final/salt/cis-controls/redhat8.sls
saltstack/final/salt/cis-controls/scripts/cis_control.sh

Create a loopback ext4 filesystem with the same size as the Azure logical volume for /tmp (12GB), back up current /tmp contents into it and mount it as /tmp with noexec option.
Azure freeipa: http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-v2/1865/
AWS arm64: http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-v2/1876/
GCP 7.2.16: http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-v2/1885/

CB-27820 Loopback filesystem mounted with noexec as /tmp

---

scripts/get-image-size.sh

```
(venv) dbajzath@dbajzath:~/workspace/cloudbreak-images$ ./scripts/get-image-size.sh Azure redhat8 "" x86_64
64
(venv) dbajzath@dbajzath:~/workspace/cloudbreak-images$ ./scripts/get-image-size.sh Azure redhat8 "7.2.18" x86_64
70
(venv) dbajzath@dbajzath:~/workspace/cloudbreak-images$ ./scripts/get-image-size.sh AWS redhat8 "" x86_64
48
(venv) dbajzath@dbajzath:~/workspace/cloudbreak-images$ ./scripts/get-image-size.sh AWS redhat8 "7.2.18" x86_64
56
```

CB-27926 Optimize image sizes

---

Makefile
saltstack/base/salt/prerequisites/usr/bin/user-data-helper.sh
saltstack/base/salt/salt-bootstrap/etc/systemd/system/salt-bootstrap.service

Previously salt-bootstrap wouldn't work with HTTPS enabled, on non-gateway instances, since we do not generate the cert files which salt-bootstrap was relying on, on these instances.
Added logic for always generating the necessary certs (given that saltboot HTTPS is enabled):
- On gateway instances, we generate them using the same ca cert used to generate the certs for nginx and jumpgate
- On all other instances, we generate a ca cert and use that to generate the necessary certs
Note: The host values in the generated certs still don't matter, as there is still neither client- nor host-side verification. We only use TLS to have the channel be encrypted.

CB-28061: Reenable HTTPS for saltboot and ensure cert files are present

---

saltstack/base/salt/luks/bin/create-luks-volume.sh
saltstack/base/salt/luks/bin/populate-luks-volume.sh
saltstack/base/salt/luks/bin/reopen-luks-volume.sh
saltstack/base/salt/userdata-secrets/bin/cdp-retrieve-userdata-secrets.sh

* `create-luks-volume.sh`:
* Pass a manually obtained LUKS volume key to `cryptsetup luksFormat`.
* The volume key is generated using `kms:GenerateRandom` with size 64 bytes / 512 bits.
* The plaintext volume key file is kept on the same `tmpfs` volume already used for the plaintext passphrase.
* Since the volume key in plaintext form is only needed at the time of `cryptsetup luksFormat` invocation, the volume key file gets immediately removed after the successful completion of this command.
* `cdp-retrieve-userdata-secrets.sh`, `create-luks-volume.sh`, `populate-luks-volume.sh`, `reopen-luks-volume.sh`:
* Prefix log messages with a timestamp header.
* Add some additional log messages for easier troubleshooting.
* Enable debug logging for AWS CLI and AWS Encryption CLI invocations.

CB-28300 Generate LUKS volume key using `kms:GenerateRandom`

---

saltstack/base/salt/prerequisites/packages.sls
saltstack/hortonworks/salt/kerberos/ad.sls
saltstack/hortonworks/salt/kerberos/init.sls

Also for ECS `iscsi-initiator-utils` is required.

CB-28374 Add AD related packages to image

---

Makefile
docker/redhat8/Dockerfile

The custom freeIPA images were built with the new version of jumpgate agent and published. The information can be found here
- https://github.com/hortonworks/cloudbreak-images/tree/jumpgate-artifact/jumpgate. 
UUIDs for the images are below:
- AWS - "33d1490c-fee2-41f7-923f-000b90c09110"
- Azure - "5a5715e4-312c-4680-a83c-13acaad44809"
- GCP - "32fc7eba-baeb-4f01-bbb1-d74d827ad89a"
E2E tests were run with the custom freeIPA images and the tests were successful. Refer
- AWS - https://quanta.infra.cloudera.com/#/runDetails?gtn=62628916
- Azure - https://quanta.infra.cloudera.com/#/runDetails?gtn=62655154
- GCP - https://quanta.infra.cloudera.com/#/runDetails?gtn=62690983

Updated jumpgate agent to 3.9.0 in freeIPA image

---

saltstack/base/salt/telemetry/init.sls

Previous version: `1.3.6-b2`
New version: `1.3.7-b2`
The TLS cipher configuration wasn't properly taken into consideration, as it wasn't applied to the actual cdp-request-signer server, only the client passed to the proxy request handler.

CB-28730: Bump cdp-request-signer version to be able to configure TLS ciphers

---

Makefile

Enable the saltboot HTTPS feature if the saltboot version has:
- minor version = 14 AND patch version >= 3
- OR
- minor version >= 15
salt-bootstrap version `0.14.3` includes:
- fallback to HTTP on port 7070 if the target is not listening for HTTPS on port 7071
- using the same timeout settings on both the HTTP and HTTPS client
- configurable TLS version and cipher suites

CB-28865: Bump saltboot version to `0.14.3` and turn HTTPS back on

---

Makefile

we need to copy azure image to region us-west-2 too in case of internal flow, because the MP is not available. So we reduced the possible available regions are being copied, just the west us 2 kept. This change affects the Centos7 image burning as well.

CB-29299: Copy Azure images for internal releases to us-west-2

---

saltstack/base/salt/prerequisites/selinux.sls
saltstack/base/salt/selinux/etc/selinux/cdp/hostname/cdp-hostname.te
saltstack/base/salt/selinux/etc/selinux/cdp/install-cdp-policies.sh
saltstack/base/salt/selinux/etc/selinux/cdp/install-hostname-policy.sh
saltstack/base/salt/selinux/etc/selinux/cdp/postgresql/cdp-postgresql.fc
saltstack/base/salt/selinux/etc/selinux/cdp/postgresql/cdp-postgresql.restorecon
saltstack/base/salt/selinux/etc/selinux/cdp/postgresql/cdp-postgresql.te
saltstack/base/salt/selinux/init.sls
saltstack/base/salt/top.sls

- Each custom policy's files should be placed in a separate subdirectory under `/etc/selinux/cdp/`. The directory should have the same name as the module, but without the `cdp-` prefix. The directory contains the necessary `.te`, `.fc` and `.if` files for the custom policy, with each file having the same name as the module's name.
- The policies are installed by the `install-cdp-policies.sh` script located in `/etc/selinux/cdp/`
- The directory can also contain a file with the `.restorecon` extension and the same name as the module's name. For each of the paths listed in this file the following command will be called by the `install-cdp-policies.sh` script: `restorecon -Rv <path>`. This ensures the file context rules defined by the cus
tom policy are applied to existing files matching the …

CB-29006,CB-29210: Apply correct SELinux file contexts to PostgreSQL related locations and refactor host name policy installation

---

saltstack/base/salt/prerequisites/usr/bin/user-data-helper.sh
saltstack/base/salt/salt-bootstrap/etc/systemd/system/salt-bootstrap.service

Saltboot certs are created in the `/etc/salt-bootstrap/certs/` directory.
The `salt-bootstrap.service` unit file was also updated to reflect this change.

CB-29126: Separate saltboot cert generation from nginx cert generation

---

Makefile

We need to distinguish a different copy phase for internal images (besides the original test phase), so the 'internal-test' phase is being introduced where a reduced region set will be used for the copy step. Basically this change just affects the azure image burning because the aws region set is the same as normal and internal cases.

CB-29374: Base images are not copied to necessary regions

---

saltstack/base/salt/hostname/etc/systemd/system/google-guest-agent.service.d/override.conf
saltstack/base/salt/hostname/init.sls
saltstack/base/salt/hostname/usr/local/bin/cleanup-hosts.sh

CB-29390 Add script and systemd unit file drop in to clean up entries added by GCP from /etc/hosts
test img burning: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/7050/console
validator run: http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-v2/3126/console

CB-29390 Add script and systemd unit file drop in to clean up entries added by GCP from /etc/host

---

scripts/packer.sh

- This adds an ARM64-specific version of the Jumpgate agent onto images built for this platform.
- The PR also adds new arm64 build URLs of freeipa health and ldap agents which became obsolete in the RE build cache and hence, the URLs returned 404
> **Note:**  

CB-29871: Added ARM64 RPM of jumpgate-agent

---

scripts/get-image-size.sh

This is for AWS Gov 7.3.1.x POC only. Validation fails at the moment, but that is expected. Burning is successful though: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/7937/

CB-30062: More space required for 7.3.1 on AWS Gov

---

Makefile
packer.json

This is just the basics, it can be safely merged as it has zero effect on existing RHEL 8 image burning.
Image burning can be started with this, but it's not enough to have full RHEL 9 support. Example:
http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/7955/console

CB-29337: Added Make and Packer opts for RHEL9

---

saltstack/final/salt/cis-controls/redhat8.sls
saltstack/final/salt/cis-controls/scripts/cis_control.sh

**Noexec tmp for CDP feature breaks AWS images**
This feature should be valid only for images >= 7.3.1 version. Currently it is valid on all aws images as the SKIP tag for noexec skipping is not assigned.
- [ x] Runtime image burning (per provider)
- [ x] Runtime image validation (per provider)
- [ -] FreeIPA image burning (per provider)
- [ -] FreeIPA image validation (per provider)
- [ -] Base image burning
- [ -] Base image validation
7.3.1.500 GCP:
http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/8012/ :white_check_mark:
5b2ebe94-fe82-4e92-822b-e76b42e04fe4
Basic: http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-v2/3678/ :white_check_mark: …

CB-30121 Noexec tmp for CDP feature breaks AWS images

---

saltstack/base/salt/prerequisites/usr/bin/user-data-helper.sh
saltstack/base/salt/selinux/etc/selinux/cdp/user-data-helper/cdp-user-data-helper.fc
saltstack/base/salt/selinux/etc/selinux/cdp/user-data-helper/cdp-user-data-helper.restorecon
saltstack/base/salt/selinux/etc/selinux/cdp/user-data-helper/cdp-user-data-helper.te
saltstack/base/salt/selinux/init.sls

Based on the obversation of [this commit](https://github.com/hortonworks/cloudbreak-images/commit/0055cda3700cba81c7014984487ea8e7b1943b86#diff-a32984e3bc0b3bc6386e001507f51eb3b2116f7cd9266a61ff1d9ffaa62be817): this script is currently run unconfined, hence most of the files it produces have incorrect file contexts. As an interim solution, execute `restorecon` for `/etc/salt-bootstrap/` and `/etc/salt-bootstrap/certs/` explicitly. This workaround can later be removed once the above ticket gets fixed.
Files that are created by this script and get bad context:
/var/log/user-data.log
/etc/salt-bootstrap/security-config.yml
/etc/salt-bootstrap/certs/ca.pem
/etc/salt-bootstrap/certs/saltboot-key.pem
/etc/salt-bootstrap/certs/saltboot.pem
The freeIPA and prewarm image have both been manually …

CB-29572 - Create SELinux policy for user-data-helper.sh

---

saltstack/base/salt/prerequisites/packages.sls

This PR has absolutely ZERO effect on any of the CentOS 7 and RHEL 8 images, so it's pointless to test them.
- AWS x86: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/8095/
- AWS ARM: RHEL 9 ARM internal mirror is broken, so ARM64 image burning is blocked by RELENG-29558
- Azure: there's nothing Azure-specific in this PR
- GCP: there's nothing GCP-specific in this PR
> **Note:**  

CB-29497: Disabled attempting to install iptables on RHEL 9

---

saltstack/base/salt/prerequisites/geoclue.sls

Cleans up some leftover trash code from https://github.com/hortonworks/cloudbreak-images/pull/1172
Zero. Zilch. Nada. :) This is just a code cleanup, basically it removes a bunch of echos and comments.
Okay, okay... I might have tested it here just to make it sure: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/8096/
> **Note:**  

CB-30169: Cleaned up Geoclue2 removal code (RHEL9 only)

---

saltstack/base/salt/prerequisites/user_uid.sls

This PR has absolutely ZERO effect on any of the CentOS 7 and RHEL 8 images, so it's pointless to test them.
- AWS x86: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/8101/ - ✅ 
- AWS ARM: RHEL 9 ARM internal mirror is broken, so ARM64 image burning is blocked by RELENG-29558
- Azure: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/8108/
- GCP: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/8109/ - ✅ 
> **Note:**  

CB-29496: Fix cloudera-scm uid/gid for RHEL9

---

scripts/packer.sh

This PR is related to RHEL9 Base image production only and it has no effect on CentOS 7 and RHEL 8 images.
> **Note:**  

CB-30181 Assume JDK 17 as the default on RHEL 9

---

saltstack/final/salt/cis-controls/init.sls
saltstack/final/salt/cis-controls/redhat9.sls

This PR is related to RHEL9 Base image production only and it has no effect on CentOS 7 and RHEL 8 images.
> **Note:**  

CB-30183: Fixed broken GPG verification

---

saltstack/base/salt/postgresql/init.sls

Make sure psql11 is not installed on rhel9, and refactor pg installations to separate steps for better error messages in case of failures
A single GCP base image burning was started but it failed on pg14 install which has a follow up in https://cloudera.atlassian.net/browse/RELENG-30791

CB-30176 Avoid installing PostgreSQL 11 on RHEL 9 images

---

saltstack/base/salt/selinux/etc/selinux/cdp/kerberos/cdp-kerberos.fc
saltstack/base/salt/selinux/init.sls

The krb5.conf file context rule was a duplicate which caused the filecon db post processing to fail every time.
The RHEL8 policycoreutils package is quite old. The semodule provided by this package version doesn't detect this conflict. On RHEL9, this conflict could be identified as the verbose log stated it. Also, for some reason the x86 version doesn't detect the conflict, but also doesn't cause the later semodule calls to fail.
Removed the file context rule. It was originally included because the file didn't seem to have the correct file context. Removing it shouldn't change anything and even if it did, since our domains are permissive, in the worst case this results in deny logs in the audit log, but no actual permission denied error.
Describe the tests that were run, and provide …

CB-30276: Fix SELinux policy install on arm

---

saltstack/final/salt/metadata/tmp/generate-package-versions.sh
scripts/salt-install.sh

Only tested with base images on RHEL 8 and 9, simply because there's no difference between Base, FreeIPA and Runtime images when it comes to Python installation - it's all done as part of the Salt install phase right at the start.
- RHEL 8 AWS: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/8396/
- RHEL 9 AWS: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/8395/
> **Note:**  

CB-30255: Install Python 3.12 on all VM images

---

scripts/packer.sh

This is just a refresh, the RPMs are the same as they were, but they have been rebuilt because build cache only retains them for a few weeks. The URLs are correct, so no special testing is needed.
> **Note:**  

CB-30382: Updated ARM64 FreeIPA Artifacts

---

saltstack/hortonworks/salt/pre-warm/cdh.sls
saltstack/hortonworks/salt/pre-warm/tmp/create_torrent.sh
saltstack/hortonworks/salt/pre-warm/tmp/install_cdh.sh

- RHEL 9 AWS 7.3.2 - http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/8461/
- RHEL 8 AWS 7.3.1 - http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/8460/
- RHEL 9 AWS 7.3.2 - http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-v2/3959/ (basic, int, failed)
- RHEL 9 AWS 7.3.2 - http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-v2/3959/ (basic, dev, failed) 
- RHEL 8 AWS 7.3.1 - http://ci-cloudbreak.eng.hortonworks.com/job/api-e2e-imagevalidator-v2/3958/ (basic)
- RHEL 8 AWS 7.3.1 - …

CB-30391: Replaced mktorrent with py3createtorrent for RHEL 9

---

saltstack/base/salt/postgresql/init.sls
scripts/salt-install.sh

This commit fixes the following Python3 related bugs:
CB-30405 - The default "pip3" now points to Python 3.9's pip3 installation rather than 3.12's, so it will be in sync with the default system Python version which is also 3.9
CB-30416 - The way we need to query the exact Python 3.9 version is slightly different on the AWS images compared to Azure and GCP. This has been fixed.
CB-30422 - PsycoPg2 library needs to be separately installed for all Python versions supported on the image. This has been missing for Python 3.12
- AWS x86 RHEL 9 7.3.2: http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/8478/
- Azure RHEL 9 7.3.2: …

CB-30405: Py3+RHEL9 fixes, read the commit msg

---

saltstack/base/salt/telemetry/init.sls

Only tested on AWS just to see the RPM is correct and version numbers look good. This is for RHEL 9 only (for now) and for RHEL 9, the validation is still broken on mow-dev and unavailable on mow-int.
- AWS - http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/8492/
- [] Base image validation

CB-30423: Removed the hardcoded override of cdp-request-signer on RHEL 9

---

Makefile

- AWS x86 - http://build.eng.hortonworks.com/job/cloudbreak-multi-packer-image-builder-salt-v3/8545/
- AWS ARM64 - will be fixed later, see RELENG-31151
- Azure - will be fixed later - apparently there's no RHEL 9.6 origin image for Azure
- GCP - not affected, it's already on RHEL 9.6
> **Note:**  

CB-30236: Updated origin images to RHEL 9.6 on AWS

---

Makefile

wrong docker registry url for yarn images

CB-30572 fixing docker repository url

---

Makefile

Fix the default (empty) value of release-id tag

CB-29338: Fix default value of release-id tag

---

saltstack/final/salt/waagent/init.sls

This change is to prevent waagent from mounting ephemeral volumes in Azure.
1.  ResourceDisk.Format is the setting name that is related to formatting the ephemeral disk. Setting this to n will prevent Azure Linux agent from automatically formatting ephemeral disks.
2.  ResourceDisk.EnableSwap is the setting name that is related to creating and configuring a swap file on the ephemeral disk. Setting this to n will disable swap file on ephemeral disks.
3.  ResourceDisk.MountPoint is the setting name that is used to specify the mount point for the ephemeral disks. Setting this to empty will inform Azure Linux agent to not mount ephemeral disks.
Describe the tests that were run, and provide Jenkins links for each …

CB-30533 - This change is to prevent waagent from mounting ephemeral volumes in Azure.
